### PR TITLE
Tokens: Implement all current operations

### LINKED ISSUE #1194: osc token --trigger should allow additional arguments
osc token --trigger --operation release only allows to pass project and package, while the `/trigger/release` route accepts also additional argments. 

https://build.opensuse.org/apidocs-new/#/Trigger/post_trigger__operation_ documents repository and arch - while IBS seems to be patched to also support targetproject and others (hurray!)

### PR DESCRIPTION
**Pull request by SchoolGuy**
Fixes #1194 

This also introduces a module that enables osc to validate the XML answers according to the XML Schemas that an OBS instance is making available.

> Note: This is a Draft atm and subject to change. However please comment your opinions as this will influence my progress heavily.

### CODE REVIEW

**Comment by SchoolGuy** [comment]
I assumed that `lxml` is used for XML parsing. It seems this would be a new dependency. I will take a look if it is possible to use the stdlib or if `lxml` is really required.

**Comment by Conan-Kudo** [comment]
`lxml` is a drop-in replacement that makes XML processing go a lot more quickly.

**Comment by SchoolGuy** [comment]
This PR is still waiting for the server-side PR to be merged. The discussion about `lxml` needs to be done once the implementation is finished.

**Comment by dmach** [comment]
I've submitted an alternative implementation that follows the latest best practices: #1550

**Comment by SchoolGuy** [comment]
I believe your new implementation @dmach is a much better fit than this PR. As such I will close my PR now.

**Pull request closed without merging**
