### PR TITLE
Add --from-csv argument to osc-results

### PR DESCRIPTION
**Pull request by yaccz**
Example usage and output:

% ./osc-wrapper.py search --package hexedit | ./osc-wrapper.py results --stdin
Results of hexedit in home:adra
openSUSE_Tumbleweed  i586       succeeded
openSUSE_Tumbleweed  x86_64     succeeded
openSUSE_13.2        i586       succeeded
openSUSE_13.2        x86_64     succeeded

Results of hexedit in home:ajorgensen
RedHat_RHEL-6        i586       succeeded
RedHat_RHEL-6        x86_64     succeeded
RedHat_RHEL-5        i586       succeeded
RedHat_RHEL-5        x86_64     succeeded

### CODE REVIEW

**Comment by marcus-h** [comment]
First of all thanks for the patch!
However, the patch is quite "complicated" and not really pythonic.
For example,
+        if opts.from_csv:
+          xs = map(lambda x: x[:-1], sys.stdin.readlines())
+          xs = map(lambda x: tuple(x.split("|")), xs)

Could be written as
xs = [line.rstrip().split('|') for line in sys.stdin.readlines()]
(which is, IMHO, more readable). In general, list comprehensions
(see https://docs.python.org/2/tutorial/datastructures.html#tut-listcomps)
or generators are preferred over maps:)

Also, we could avoid the "NResultsPrintJoin" class.

IMHO, a straightforward implementation would just collect the
project, project/package data and then simply iterates over
the collected data, queries the api and prints the results.

What do you think?

**Comment by yaccz** [comment]
Comprehensions yes but I don't want to rewrite the print join as that would require more invasive refactoring I don't want to get into.

**Comment by yaccz** [comment]
What do you think?

**Comment by yaccz** [comment]
Hello, I've pushed new code which should be more reasonable. Let me know what you think, please.

**Comment by marcus-h** [comment]
On 2015-10-23 10:04:23 -0700, Jan Matějka wrote:
> Hello, I've pushed new code which should be more reasonable. Let me know what you think, please.
> 
First of all, sorry for the late response. I'll review your
changes at the end of the week (at the latest).

**Pull request closed without merging**
