### PR TITLE
prepend request summary to diff in interactive mode

### PR DESCRIPTION
**Pull request by lethliel**
makes it easier for reviewers to get the summary information without the use to exit 
the diff mode.

@marcus-h: please review

### CODE REVIEW

**Comment by marcus-h** [comment]
On 2017-10-10 09:34:04 +0000, Marco Strigl wrote:
> makes it easier for reviewers to get the summary information without the use to exit 
> the diff mode.
> 
> @marcus-h: please review

> diff --git a/osc/core.py b/osc/core.py
> index beb78b12..0a31bdd3 100644
> --- a/osc/core.py
> +++ b/osc/core.py
> @@ -7216,20 +7216,30 @@ def print_source_buildstatus(src_actions, newline=False):
>              else:
>                  repl = raw_input(prompt).strip()
>              if repl == 'i' and src_actions:
> +                # we need to store stdout to a variable (request_sum),
> +                # because print_requests prints directly and we want
> +                # to append the output of print to the diff
> +                org_stdout = sys.stdout
> +                request_sum = StringIO()
> +                sys.stdout = request_sum
> +                print_request(request)
> +                # restore original stdout
> +                sys.stdout = org_stdout
> +                diff = request_sum.getvalue()

Hmm "a bit complicated". What about
diff = str(request) + '\n'

>                  if not orequest is None and tmpfile:
>                      tmpfile.close()
>                      tmpfile = None
>                  if tmpfile is None:
>                      tmpfile = tempfile.NamedTemporaryFile(suffix='.diff')
>                      try:
> -                        diff = request_diff(apiurl, request.reqid)
> +                        diff += request_diff(apiurl, request.reqid)
>                          tmpfile.write(diff)
>                      except HTTPError as e:
>                          if e.code != 400:
>                              raise
>                          # backward compatible diff for old apis
>                          for action in src_actions:
> -                            diff = 'old: %s/%s\nnew: %s/%s\n' % (action.src_project, action.src_package,
> +                            diff += 'old: %s/%s\nnew: %s/%s\n' % (action.src_project, action.src_package,
>                                  action.tgt_project, action.tgt_package)

This is "wrong" in case of len(source_actions) > 1, because in the
i-th iteration (i > 1), it'll write the "accumulated" diff of
iteration i - 1 again (see tmpfile.write(diff)). Just add a
tmpfile.write(diff) before the loop and leave the loop body as is.

>                              diff += submit_action_diff(apiurl, action)
>                              diff += '\n\n'
>

**Comment by marcus-h** [comment]
The new version looks almost good!

On 2017-10-10 09:34:04 +0000, Marco Strigl wrote:
> diff --git a/osc/core.py b/osc/core.py
> index beb78b12..ca04d9ee 100644
> --- a/osc/core.py
> +++ b/osc/core.py
> @@ -7216,18 +7216,21 @@ def print_source_buildstatus(src_actions, newline=False):
>              else:
>                  repl = raw_input(prompt).strip()
>              if repl == 'i' and src_actions:
> +                req_summary = str(request) + '\n'
>                  if not orequest is None and tmpfile:
>                      tmpfile.close()
>                      tmpfile = None
>                  if tmpfile is None:
>                      tmpfile = tempfile.NamedTemporaryFile(suffix='.diff')
>                      try:
> +                        tmpfile.write(req_summary)
>                          diff = request_diff(apiurl, request.reqid)
>                          tmpfile.write(diff)
>                      except HTTPError as e:
>                          if e.code != 400:
>                              raise
>                          # backward compatible diff for old apis
> +                        tmpfile.write(req_summary)

You might end up with a double write of "req_summary". (Also, there
is no need to move the tmpfile.write(...) into the try block.)
Otherwise, LGTM.

**Comment by lethliel** [comment]
On 10/10/2017 04:44 PM, Marcus Hüwe  wrote:
> 
> You might end up with a double write of "req_summary". (Also, there
> is no need to move the tmpfile.write(...) into the try block.)
> Otherwise, LGTM.
>
You mean just one tempfile.write(req_summary) before the try block?

**Comment by lethliel** [comment]
@marcus-h: please review again. 

I removed the tempfile.write(req_summary) lines from the try... except block and moved 
added it in front.

**Comment by marcus-h** [comment]
On 2017-10-11 06:57:32 +0000, Marco Strigl wrote:
> @marcus-h: please review again. 
> 
> I removed the tempfile.write(req_summary) lines from the try... except block and moved 
> added it in front. 
> 
Thanks! Merged.

**Pull request merged**
