### PR TITLE
show issues (bugs) in interactive review diff

### PR DESCRIPTION
**Pull request by lethliel**
To get a better overview in the interactive review mode the issues connected to 
the submitrequest are shown. 

Additionally to the bugnumber the following information will be shown: 

- Summary
- Status

The output looks like this

`## BUG# boo#123456: This is the summary to the describe the bug in a short form : OPEN`

@marcus-h: Please review

### CODE REVIEW

**Comment by marcus-h** [comment]
Hi,

I just had a quick glance at it.

On 2017-10-16 05:15:21 -0700, Marco Strigl wrote:
> +def get_request_issues(apiurl, reqid):
> +    """
> +    gets a request xml with the issues for the request inside and creates
> +    a list 'issue_list' with a dict of the relevant information for the issues.
> +    This only works with bugtrackers we can access, like buzilla.o.o
> +    """
> +    u = makeurl(apiurl, ['request', reqid], query={'cmd': 'diff', 'view': 'xml', 'withissues': '1'} )
> +    f = http_POST(u)
> +    print(u)

Hmm debug code?:)

> +    request_tree = ET.parse(f).getroot()
> +    issue_list = []
> +    for elem in request_tree.iterfind('action/sourcediff/issues/issue'):
> +        if re.match(r"[Bb][NnSsOo][CcOo]#\d+", elem.get('label')) is None:
> +            # we do not have enough information from other bugtrackers
> +            continue

Hmm I'm not really fond of hardcoding this. Just do the API call (I think
in the worst case we just get an empty collection).

> +        issue = {}
> +        issue_id = elem.get('name')
> +        encode_search = '@name=' + str(issue_id)

issue_id is already a string. Something like this cannot harm

encode_search = "@name = '%s'" % issue_id

> +        u = makeurl(apiurl, ['search/issue'], query={'match': encode_search} )
> +        f = http_GET(u)
> +        collection = ET.parse(f).getroot()
> +        if collection.get('matches') > 0:

This always holds (the get call returns a string).

> +            for cissue in collection:
> +                for issue_detail in cissue.iter():
> +                    issue[issue_detail.tag] = issue_detail.text.strip()

Hmm can the tag names clash if the collections contains more than
1 element?

> +        issue_list.append(issue)
> +    return issue_list
> +
> +def print_request_issues(apiurl, reqid):
> +    """get issue_list and return a printable string"""
> +    issue_list = get_request_issues(apiurl, reqid)
> +    issues = ""
> +    for issue in issue_list:
> +        issues += "## BUG# " + issue['label'] + ": " + issue.get('summary', 'nv') + " : " + issue.get('state', 'nv') + '\n'
> +    return issues

IMHO the function name is a bit misleading. I think the best is to move
this function into "def request_interactive_review".

> +
>  def submit_action_diff(apiurl, action):
>      """diff a single submit action"""
>      # backward compatiblity: only a recent api/backend supports the missingok parameter
> @@ -7224,12 +7260,14 @@ def print_source_buildstatus(src_actions, newline=False):
>                  repl = raw_input(prompt).strip()
>              if repl == 'i' and src_actions:
>                  req_summary = str(request) + '\n'
> +                issues = '\n\n' + print_request_issues(apiurl, request.reqid)
>                  if not orequest is None and tmpfile:
>                      tmpfile.close()
>                      tmpfile = None
>                  if tmpfile is None:
>                      tmpfile = tempfile.NamedTemporaryFile(suffix='.diff')
>                      tmpfile.write(req_summary)
> +                    tmpfile.write(issues)
>                      try:
>                          diff = request_diff(apiurl, request.reqid)

Hmm now we retrieve the "source diff" two times.

**Comment by lethliel** [comment]
On 10/17/2017 07:16 PM, Marcus Hüwe  wrote:
> Hi,
> 
> I just had a quick glance at it.
> 

Thank you :)

> On 2017-10-16 05:15:21 -0700, Marco Strigl wrote:
>> +def get_request_issues(apiurl, reqid):
>> + """
>> + gets a request xml with the issues for the request inside and creates
>> + a list 'issue_list' with a dict of the relevant information for the issues.
>> + This only works with bugtrackers we can access, like buzilla.o.o
>> + """
>> + u = makeurl(apiurl, ['request', reqid], query={'cmd': 'diff', 'view': 'xml', 'withissues': '1'} )
>> + f = http_POST(u)
>> + print(u)
> 
> Hmm debug code?:)
>

hrm. Yes will remove it. 

>> + request_tree = ET.parse(f).getroot()
>> + issue_list = []
>> + for elem in request_tree.iterfind('action/sourcediff/issues/issue'):
>> + if re.match(r"[Bb][NnSsOo][CcOo]#\d+", elem.get('label')) is None:
>> + # we do not have enough information from other bugtrackers
>> + continue
> 
> Hmm I'm not really fond of hardcoding this. Just do the API call (I think
> in the worst case we just get an empty collection).
>

The collection would not be empty. There will be no additional information (like summary, 
state and reporter). And IMHO it makes no sense to list just the buglabel to have something like this:

## BUG# kde#123456: nv : nv
## BUG# kde#234567: nv : nv
## BUG# kde#124456: nv : nv
## BUG# kde#123356: nv : nv
## BUG# kde#133456: nv : nv

So I decided to filter it and make no api calls to get details for bugs we do not 
have the details for. 

But if you do not want to have it hardcoded we could move the pattern in the configuration. 
Would that be an option?
 
>> + issue = {}
>> + issue_id = elem.get('name')
>> + encode_search = '@name=' + str(issue_id)
> 
> issue_id is already a string. Something like this cannot harm
> 
> encode_search = "@name = '%s'" % issue_id
> 

Ok. Will look at it again.

>> + u = makeurl(apiurl, ['search/issue'], query={'match': encode_search} )
>> + f = http_GET(u)
>> + collection = ET.parse(f).getroot()
>> + if collection.get('matches') > 0:
> 
> This always holds (the get call returns a string).
> 
>> + for cissue in collection:
>> + for issue_detail in cissue.iter():
>> + issue[issue_detail.tag] = issue_detail.text.strip()
> 
> Hmm can the tag names clash if the collections contains more than
> 1 element?
> 

I don't think so. Because I have never ever seen more than one issue in a 
collection. Not even sure why the xml is formed that way. 

>> + issue_list.append(issue)
>> + return issue_list
>> +
>> +def print_request_issues(apiurl, reqid):
>> + """get issue_list and return a printable string"""
>> + issue_list = get_request_issues(apiurl, reqid)
>> + issues = ""
>> + for issue in issue_list:
>> + issues += "## BUG# " + issue['label'] + ": " + issue.get('summary', 'nv') + " : " + issue.get('state', 'nv') + '\n'
>> + return issues
> 
> IMHO the function name is a bit misleading. I think the best is to move
> this function into "def request_interactive_review".
> 

Yes. You are right. Will move it. 

>> +
>> def submit_action_diff(apiurl, action):
>> """diff a single submit action"""
>> # backward compatiblity: only a recent api/backend supports the missingok parameter
>> @@ -7224,12 +7260,14 @@ def print_source_buildstatus(src_actions, newline=False):
>> repl = raw_input(prompt).strip()
>> if repl == 'i' and src_actions:
>> req_summary = str(request) + '\n'
>> + issues = '\n\n' + print_request_issues(apiurl, request.reqid)
>> if not orequest is None and tmpfile:
>> tmpfile.close()
>> tmpfile = None
>> if tmpfile is None:
>> tmpfile = tempfile.NamedTemporaryFile(suffix='.diff')
>> tmpfile.write(req_summary)
>> + tmpfile.write(issues)
>> try:
>> diff = request_diff(apiurl, request.reqid)
> 
> Hmm now we retrieve the "source diff" two times.
>

Yes. The problem is that the source diff in request_diff is completely different from the one i need
to get the issues. 

One (the original api call in request_diff) returns text and the one I need returns xml from 
which I need to extract the issues. 

So either we have to api calls or I change the request_diff function to handle the returned xml.

**Comment by lethliel** [comment]
@marcus-h: 

- removed debug code :-)
- moved the function to the right place
- and changed the way I build the encode_search variable

**Comment by marcus-h** [comment]
On 2017-10-17 11:24:28 -0700, Marco Strigl wrote:
> On 10/17/2017 07:16 PM, Marcus Hüwe  wrote:
> > On 2017-10-16 05:15:21 -0700, Marco Strigl wrote:
> >> + request_tree = ET.parse(f).getroot()
> >> + issue_list = []
> >> + for elem in request_tree.iterfind('action/sourcediff/issues/issue'):
> >> + if re.match(r"[Bb][NnSsOo][CcOo]#\d+", elem.get('label')) is None:
> >> + # we do not have enough information from other bugtrackers
> >> + continue
> > 
> > Hmm I'm not really fond of hardcoding this. Just do the API call (I think
> > in the worst case we just get an empty collection).
> >
> 
> The collection would not be empty.

Ah ok. I just checked non-existent "names".

> There will be no additional information (like summary, 
> state and reporter). And IMHO it makes no sense to list just the buglabel to have something like this:
> 
> ## BUG# kde#123456: nv : nv
> ## BUG# kde#234567: nv : nv
> ## BUG# kde#124456: nv : nv
> ## BUG# kde#123356: nv : nv
> ## BUG# kde#133456: nv : nv
> 
Hmm I could live with that. Btw., what's the meaning of "nv"? (Maybe
use "unknown" or "unknown summary : unknown state"?)

> So I decided to filter it and make no api calls to get details for bugs we do not 
> have the details for. 
> 
This could also happen for boo/bnc bugs:

marcus@linux:~/home:Marcus_H/issue_test> curl -u Marcus_H https://api.opensuse.org/search/issue?match=%40name%3D%27385140%27%20and%20%40tracker%3D%27bnc%27
Enter host password for user 'Marcus_H':
<collection matches="1">
  <issue>
    <created_at>2017-10-18 13:39:04 UTC</created_at>
    <updated_at>2017-10-18 13:39:04 UTC</updated_at>
    <name>385140</name>
    <tracker>bnc</tracker>
    <label>boo#385140</label>
    <url>https://bugzilla.opensuse.org/show_bug.cgi?id=385140</url>
  </issue>
</collection>marcus@linux:~/home:Marcus_H/issue_test>

> But if you do not want to have it hardcoded we could move the pattern in the configuration. 
> Would that be an option?
>  
Hmm I'm not sure if it makes sense to make this a config option,
because it usually depends on the API (+ its configuration) you are
communicating with: a private obs instance might fetch the issues
for kde, but not for boo/bnc.

> >> + for cissue in collection:
> >> + for issue_detail in cissue.iter():
> >> + issue[issue_detail.tag] = issue_detail.text.strip()
> > 
> > Hmm can the tag names clash if the collections contains more than
> > 1 element?
> > 
> 
> I don't think so. Because I have never ever seen more than one issue in a 
> collection. Not even sure why the xml is formed that way. 
> 
Hmm it can happen. For instance,

marcus@linux:~/home:Marcus_H/issue_test> curl -u Marcus_H https://api.opensuse.org/search/issue?match=%40name%3D%27385140%27
Enter host password for user 'Marcus_H':
<collection matches="4">
  <issue>
    <created_at>2017-10-17 15:29:14 UTC</created_at>
    <updated_at>2017-10-17 15:29:14 UTC</updated_at>
    <name>385140</name>
    <tracker>kde</tracker>
    <label>kde#385140</label>
    <url>https://bugs.kde.org/show_bug.cgi?id=385140</url>
  </issue>
  <issue>
    <created_at>2017-10-18 13:39:04 UTC</created_at>
    <updated_at>2017-10-18 13:39:04 UTC</updated_at>
    <name>385140</name>
    <tracker>bnc</tracker>
    <label>boo#385140</label>
    <url>https://bugzilla.opensuse.org/show_bug.cgi?id=385140</url>
  </issue>
  <issue>
    <created_at>2017-10-18 13:41:37 UTC</created_at>
    <updated_at>2017-10-18 13:41:37 UTC</updated_at>
    <name>385140</name>
    <tracker>obs</tracker>
    <label>obs#385140</label>
    <url>https://github.com/openSUSE/open-build-service/issues/385140</url>
  </issue>
  <issue>
    <created_at>2017-10-18 13:41:37 UTC</created_at>
    <updated_at>2017-10-18 13:41:37 UTC</updated_at>
    <name>385140</name>
    <tracker>osc</tracker>
    <label>osc#385140</label>
    <url>https://github.com/openSUSE/osc/issues/385140</url>
  </issue>
</collection>marcus@linux:~/home:Marcus_H/issue_test>

We can deal with this by making the issue_list a
"list of lists of dicts".

> >> def submit_action_diff(apiurl, action):
> >> """diff a single submit action"""
> >> # backward compatiblity: only a recent api/backend supports the missingok parameter
> >> @@ -7224,12 +7260,14 @@ def print_source_buildstatus(src_actions, newline=False):
> >> repl = raw_input(prompt).strip()
> >> if repl == 'i' and src_actions:
> >> req_summary = str(request) + '\n'
> >> + issues = '\n\n' + print_request_issues(apiurl, request.reqid)
> >> if not orequest is None and tmpfile:
> >> tmpfile.close()
> >> tmpfile = None
> >> if tmpfile is None:
> >> tmpfile = tempfile.NamedTemporaryFile(suffix='.diff')
> >> tmpfile.write(req_summary)
> >> + tmpfile.write(issues)
> >> try:
> >> diff = request_diff(apiurl, request.reqid)
> > 
> > Hmm now we retrieve the "source diff" two times.
> >
> 
> Yes. The problem is that the source diff in request_diff is completely different from the one i need
> to get the issues. 
> 
> One (the original api call in request_diff) returns text and the one I need returns xml from 
> which I need to extract the issues. 
> 
> So either we have to api calls or I change the request_diff function to handle the returned xml.
> 
As discussed (and agreed (I think?)) on irc, we can easily get rid
of this, once the api supports "onlyissues=1" for a request diff.

**Comment by marcus-h** [comment]
On 2017-10-18 12:08:52 +0000, Marco Strigl wrote:
> @marcus-h: 
> 
> - removed debug code :-)
> - moved the function to the right place

Hmm the name is still misleading (nothing is printed).

> +        collection = ET.parse(f).getroot()
> +        if collection.get('matches') > 0:

This always holds.

> +            for cissue in collection:

**Comment by lethliel** [comment]
@marcus-h: 

* renamed the function to get_formatted_issues
* removed the if (not needed)
* renamed 'nv' into something more specific
* added all subissues for a collection to the list

I would like to keep the filter on bnc / boo / bso. If made a few tests and if you would use all 
bugtrackers you could get real long lists (In one example I had a collection of more than 1000 CVEs.)

And I think the most important Bugs for the reviewers are those.

**Comment by marcus-h** [comment]
On 2017-10-19 07:51:14 +0000, Marco Strigl wrote:
> @marcus-h: 
> 
> * renamed the function to get_formatted_issues
> * removed the if (not needed)
> * renamed 'nv' into something more specific

Thanks!

> * added all subissues for a collection to the list
> 
This code is still a bit buggy

> +    issue_list = []
> +    cissues_list = []
> +    for elem in request_tree.iterfind('action/sourcediff/issues/issue'):
> +        if re.match(r"[Bb][NnSsOo][CcOo]#\d+", elem.get('label')) is None:
> +            # we do not have enough information from other bugtrackers
> +            continue
> +        issue = {}

"issue" is defined too early.

> +        issue_id = elem.get('name')
> +        encode_search = '@name=%s' % issue_id
> +        u = makeurl(apiurl, ['search/issue'], query={'match': encode_search} )
> +        f = http_GET(u)
> +        collection = ET.parse(f).getroot()
> +        for cissue in collection:

issue = {} should be added here

> +            for issue_detail in cissue.iter():
> +                issue[issue_detail.tag] = issue_detail.text.strip()
> +            cissues_list.append(issue)
> +        issue_list.extend(cissues_list)

cissue_list is never cleared. Hence, we end up with a lot of
duplicates in issue_list.
Btw., instead of introducing a cissue_list, we could directly
do something like "issue_list.append(issue)".

> I would like to keep the filter on bnc / boo / bso. If made a few tests and if you would use all 
> bugtrackers you could get real long lists (In one example I had a collection of more than 1000 CVEs.)
> 
Hmm did you perform the test with the code from above? If so, then
number of "real" issues is probably roughly around 46.

> And I think the most important Bugs for the reviewers are those. 
> 
Hmm I still don't like the filtering, because it is too obs-instance
specific... What do you think about one of the following alternatives?

- in case of missing information, we just print something like
  "Unable to get information for the following issues: kde#123, bgo#456..."
- we do the filtering in get_formatted_issues (then we have at least a
  "general" get_request_issues function)

**Comment by lethliel** [comment]
@marcus-h 

I changed the following: 

* added apostrophes to encode_search string
* The requests are no longer filtered. All bugs we cannot get detailed information to are now in the format: `## No details for issue(s): kde#1234 foo#1234`
* I added an additional list to work around https://github.com/openSUSE/open-build-service/issues/4044 to prevent double entries. It is not nice, but will be removed as soon as the issue get fixed.

**Comment by marcus-h** [comment]
On 2017-10-20 08:13:19 +0000, Marco Strigl wrote:
> I changed the following: 
> 
> * added apostrophes to encode_search string
> * The requests are no longer filtered. All bugs we cannot get detailed information to are now in the format: `## No details for issue(s): kde#1234 foo#1234`
> * I added an additional list to work around https://github.com/openSUSE/open-build-service/issues/4044 to prevent double entries. It is not nice, but will be removed as soon as the issue get fixed. 
> 
Awesome! Two last nitpicks:
- please remove the unused "cissue_list" in get_request_issues
- issue.has_key('summary') should be rewritten to 'summary' in issue
  (at least if we care about python3 compatibility)

Btw.,
> +            if issue.has_key('summary'):
> +                issues += ("## BUG# " + issue['label'] + ": "
> +                          + issue.get('summary', 'unknown summary') + " : "

The summary key always exists:)

**Comment by lethliel** [comment]
On 10/20/2017 12:30 PM, Marcus Hüwe  wrote:
> On 2017-10-20 08:13:19 +0000, Marco Strigl wrote:
> - please remove the unused "cissue_list" in get_request_issues

ups. removed.

> - issue.has_key('summary') should be rewritten to 'summary' in issue
> (at least if we care about python3 compatibility)

changed.

> Btw.,
>> + if issue.has_key('summary'):
>> + issues += ("## BUG# " + issue['label'] + ": "
>> + + issue.get('summary', 'unknown summary') + " : "
> 
> The summary key always exists:)
>

Ah. Of course. Changed it.

**Comment by lethliel** [comment]
@marcus-h: Please review
and thanks for your patience with me :)

**Comment by marcus-h** [comment]
On 2017-10-20 11:06:53 +0000, Marco Strigl wrote:
> @marcus-h: Please review
> and thanks for your patience with me :)
> 
Merged. Thanks a lot!

**Pull request merged**
