### PR TITLE
Handle bytes vs. str error when parsing meta (#683)

### PR DESCRIPTION
**Pull request by krig**
In all the cases where meta_exists returns either
string data, bytes data or a list, the output needs
to be parsed correctly.

Signed-off-by: Kristoffer Grönlund <kgronlund@suse.com>

### CODE REVIEW

**Comment by marcus-h** [comment]
On 2019-11-18 00:39:40 -0800, Kristoffer Grönlund wrote:
> In all the cases where meta_exists returns either
> string data, bytes data or a list, the output needs
> to be parsed correctly.
>
Hmm maybe we should simply fix meta_exists once and for all...
I need to think about it.

**Comment by lethliel** [comment]
@marcus-h Have you thought about his? Otherwise I would like to merge this.

**Comment by marcus-h** [comment]
On 2020-02-06 01:58:14 -0800, Marco Strigl wrote:
> @marcus-h Have you thought about his?

Yes... conclusion: the whole meta_exists implementation is completely
insane and misleading (we even have code that does something like
"if meta_exists(...): ... else: ...").
The only sane thing would be a cleanup, but I'm not sure when I have
time for it...

About the patch: the patch itself is OK (except that we call
parse_meta_to_string(...) even if it is not needed (it is only
needed if the "create" parameter is set to True)). Also, it misses
one caller in commandline.py (the one in do_importsrcpkg) (I haven't,
checked the ones in core.py, though).

> Otherwise I would like to merge this.
>
I don't want to block this. Since it works around real bugs, it
is (IMHO) OK to accept the patch as-is...

@krig: are you in the mood for fixing the caller in commandline.py?

(Btw., sorry for the long delay!:/ )

**Comment by krig** [comment]
@marcus-h Sure, I'll take a look at that

**Comment by krig** [comment]
@marcus-h I think I found the one you meant, but please do double-check :)

**Comment by marcus-h** [comment]
On 2020-02-07 01:03:20 -0800, Kristoffer Grönlund wrote:
> @marcus-h I think I found the one you meant, but please do double-check :)
>
Awesome! Thanks a lot for the patch! (And your patience;) )
Merged.

**Pull request merged**
