### PR TITLE
add support for building preinstall images

### PR DESCRIPTION
**Pull request by dirkmueller**
This is yet another build type supported by the obs-build
script intended to build images that speed up the build setup
phase.

### CODE REVIEW

**Comment by marcus-h** [comment]
On 2022-01-30 15:21:17 -0800, Dirk Mueller wrote:
...
> +    if build_as_user() or build_type == 'preinstallimage':
>         # preinstallimage extraction will fail
>         bi.preinstallimage = None

Hmm why is this needed?

Btw., could you also add the missing "_preinstallimage" pieces to
"def parse_repoarchdescr" in commandline.py? (Just to support the
"_preinstallimage" file autodetection.)

Thanks a lot for the patch!

**Comment by dirkmueller** [comment]
>  +    if build_as_user() or build_type == 'preinstallimage':
>         # preinstallimage extraction will fail
>         bi.preinstallimage = None
> Hmm why is this needed?

when you fetch the preinstallimage, it will be unpacked and then repackaged into the preinstallimage making it twice as big as before. server side there must be  a hack somewhere to build with --nopreinstallimage --clean and this is supposed to fake that on local builds.

**Comment by dirkmueller** [comment]
@marcus-h  any remaining concern?

**Comment by dirkmueller** [comment]
@dmach  could you please review this as well? it blocks the "helm building" support that I'd really like to get in.

**Comment by dmach** [comment]
> > * if build_as_user() or build_type == 'preinstallimage':
> >   # preinstallimage extraction will fail
> >   bi.preinstallimage = None
> >   Hmm why is this needed?
> 
> when you fetch the preinstallimage, it will be unpacked and then repackaged into the preinstallimage making it twice as big as before. server side there must be a hack somewhere to build with --nopreinstallimage --clean and this is supposed to fake that on local builds.

Could you add this or a similar explanation to the code?
It would be good to keep it there, because nobody will probably track it to this PR when trying to understand what the code does.
Looks good to me otherwise.

**Pull request merged**
