### PR TITLE
add proper reporuls

### PR DESCRIPTION
**Pull request by lethliel**
for use in Arch, Debian and Ubuntu

Fixes https://github.com/openSUSE/osc/issues/201

### CODE REVIEW

**Comment by marcus-h** [comment]
On 2020-09-17 02:33:08 -0700, Marco Strigl wrote:
> for use in Arch, Debian and Ubuntu
>
> This is not the best fix, but unless we have a API route to get the repo-type for a repository this is the best I can do now.
>
Hmm what about something like this

import tempfile


def do_repourls(...):
    def _repo_type(apiurl, project, repo):
        # hmm or a new function query_config(apiurl, project, repo, setting)
        # in core?
        if not os.path.exists('/usr/lib/build/queryconfig'):
            return None
        build_config = get_buildconfig(apiurl, project, repo)
        with tempfile.NamedTemporaryFile() as f:
            f.write(build_config)
            f.flush()
            repo_type = return_external('/usr/lib/build/queryconfig', '--dist',
                                        f.name, 'repotype')
            if not repo_type:
                # hmm returning None is not good - we should probably do the
                # same heuristic as bs_publish
                return None
            return decode_it(repo_type)
...
    for repo in repos:
        repo_type = _repo_type(apiurl, project, repo)
        if repo_type == 'rpm-md':
            ...
        elif repo_type == 'arch':
            ...
        else:
            # default or error out?


What do you think?

**Comment by nickbroon** [comment]
Yes I think using some form of repo type information would be necessary.
Using the repo name as an approximation will not work in many of the use cases I have as the repos are often just 'standard' for debian, or sometimes a codes name like 'stretch', 'buster'.

**Comment by lethliel** [comment]
@marcus-h 

Yes. This slows down the output a little bit, but I can live with it. 
The guessing of the repotype based on the names would work with OBS but the solution of Marcus is of course better.

**Comment by marcus-h** [comment]
On 2020-09-18 04:33:57 -0700, Marco Strigl wrote:
> Yes. This slows down the output a little bit, but I can live with it.

Yes, definitely:/

> +        def _repo_type(apiurl, project,repo):
> +            if not os.path.exists('/usr/lib/build/queryconfig'):
> +                return None
> +            build_config = get_buildconfig(apiurl, project, repo)
> +            with tempfile.NamedTemporaryFile() as f:
> +                f.write(build_config)
> +                f.flush()
> +                repo_type = return_external('/usr/lib/build/queryconfig', '--dist',
> +                                        f.name, 'repotype')
> +            if repo_type is None:
> +                return None
> +            return decode_it(repo_type)
>
>          apiurl = self.get_api_url()
>
> @@ -4407,10 +4421,19 @@ def do_repourls(self, subcmd, opts, *args):
>          if elm is None or not elm.text:
>              raise oscerr.APIError('download_url configuration element expected')
>
> +        url_deb_tmpl = 'deb ' + elm.text + '/%s/%s/ /'
> +        url_arch_tmpl = 'Server=' + elm.text + '/%s/%s/$arch'
>          url_tmpl = elm.text + '/%s/%s/%s.repo'
>          repos = get_repositories_of_project(apiurl, project)
>          for repo in repos:
> -            print(url_tmpl % (project.replace(':', ':/'), repo, project))
> +            repo_type = (_repo_type(apiurl, project, repo)).rstrip('\n')

Good catch! A minor suggestion: let's move the strip to the _repo_type
function: return_external(...).rstrip('\n'). And then

if not repo_type:
    return None

(in _repo_type)

This "feels" a bit cleaner - but feel free to ignore it. Your current code
works:)

**Comment by nickbroon** [comment]
Should probably also update the help string to remove 'yum-style' and also the 'opensuse.org'.

```
    def do_repourls(self, subcmd, opts, *args):
        """${cmd_name}: Shows URLs of .repo files
        Shows URLs on which to access the project .repos files (yum-style
        metadata) on download.opensuse.org.
        usage:
           osc repourls [PROJECT]
        ${cmd_option_list}
```

**Comment by lethliel** [comment]
all done. Will merge now.

**Pull request merged**
