### PR TITLE
fix hdmrd5 check of local cached files for non-rpms

### PR DESCRIPTION
**Pull request by adrianschroeter**
This was not pushed yesterday by mistake

### CODE REVIEW

**Comment by adrianschroeter** [comment]
@marcus-h sorry, this was supposed to be push before my last comment yesterday.

**Comment by marcus-h** [comment]
On 2021-10-13 23:49:24 -0700, Adrian Schröter wrote:
> diff --git a/osc/build.py b/osc/build.py
> index 97117d54..b07c987f 100644
> --- a/osc/build.py
> +++ b/osc/build.py
> @@ -1288,6 +1288,8 @@ def __str__(self):
>
>      for i in bi.deps:
>          if i.hdrmd5:
> +            if not i.name.startswith('container:') and not i.fullfilename.endswith('.rpm'):
> +                next

s/next/continue/

>              from .util import packagequery
>              if i.name.startswith('container:'):
>                  hdrmd5 = dgst(i.fullfilename)
> diff --git a/osc/fetch.py b/osc/fetch.py
> index 3c1432cb..b99a7a4a 100644
> --- a/osc/fetch.py
> +++ b/osc/fetch.py
> @@ -217,6 +217,8 @@ def run(self, buildinfo):
>
>              if os.path.exists(i.fullfilename):
>                  cached += 1
> +                if not i.name.startswith('container:') and not i.fullfilename.endswith('.rpm'):

(We could also use i.pacsuffix != 'rpm' instead of the fullfilename
check but feel free to leave it as is.)

> +                    next

s/next/continue/

>                  if i.hdrmd5:
>                      from .util import packagequery
>                      if i.name.startswith('container:'):

**Comment by adrianschroeter** [comment]
On Donnerstag, 14. Oktober 2021, 19:46:04 CEST Marcus Hüwe wrote:
> On 2021-10-13 23:49:24 -0700, Adrian Schröter wrote:
> > diff --git a/osc/build.py b/osc/build.py
> > index 97117d54..b07c987f 100644
> > --- a/osc/build.py
> > +++ b/osc/build.py
> > @@ -1288,6 +1288,8 @@ def __str__(self):
> >
> >      for i in bi.deps:
> >          if i.hdrmd5:
> > +            if not i.name.startswith('container:') and not i.fullfilename.endswith('.rpm'):
> > +                next
> 
> s/next/continue/
> 
> >              from .util import packagequery
> >              if i.name.startswith('container:'):
> >                  hdrmd5 = dgst(i.fullfilename)
> > diff --git a/osc/fetch.py b/osc/fetch.py
> > index 3c1432cb..b99a7a4a 100644
> > --- a/osc/fetch.py
> > +++ b/osc/fetch.py
> > @@ -217,6 +217,8 @@ def run(self, buildinfo):
> >
> >              if os.path.exists(i.fullfilename):
> >                  cached += 1
> > +                if not i.name.startswith('container:') and not i.fullfilename.endswith('.rpm'):
> 
> (We could also use i.pacsuffix != 'rpm' instead of the fullfilename
> check but feel free to leave it as is.)
> 
> > +                    next
> 
> s/next/continue/
> 

yes, will update as soon as github allows me to push again ...

-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by marcus-h** [comment]
On 2021-10-14 23:07:29 -0700, Adrian Schröter wrote:
> diff --git a/osc/build.py b/osc/build.py
> index 97117d54..67b81244 100644
> --- a/osc/build.py
> +++ b/osc/build.py
> @@ -1288,6 +1288,8 @@ def __str__(self):
>
>      for i in bi.deps:
>          if i.hdrmd5:
> +            if not i.name.startswith('container:') and not i.pacsuffix != 'rpm':
> +                continue

This should should be

if not i.name.startswith('container:') and i.pacsuffix != 'rpm':
    ...

>              from .util import packagequery
>              if i.name.startswith('container:'):
>                  hdrmd5 = dgst(i.fullfilename)
> diff --git a/osc/fetch.py b/osc/fetch.py
> index 3c1432cb..a479343c 100644
> --- a/osc/fetch.py
> +++ b/osc/fetch.py
> @@ -217,6 +217,8 @@ def run(self, buildinfo):
>
>              if os.path.exists(i.fullfilename):
>                  cached += 1
> +                if not i.name.startswith('container:') and not i.pacsuffix != 'rpm':
> +                    continue

As above.

>                  if i.hdrmd5:
>                      from .util import packagequery
>                      if i.name.startswith('container:'):

**Pull request merged**
