### PR TITLE
osc shell/chroot is now handled via build script (working for chroot …

### PR DESCRIPTION
**Pull request by adrianschroeter**
…and KVM only atm)

We had bugreports about not matching mount points when using "osc chroot", so using the build script implementation now only. This should work for chroot and KVM at least, but I might have missed some special cases. So please review :)

### CODE REVIEW

**Comment by adrianschroeter** [comment]
JFYI, you need git master of the build script to get "build --shell" working for chroot

**Comment by marcus-h** [comment]
On 2019-01-09 14:19:08 +0000, Adrian Schröter wrote:
> …and KVM only atm)
> 
> We had bugreports about not matching mount points when using "osc chroot", so using the build script implementation now only. This should work for chroot and KVM at least, but I might have missed some special cases. So please review :)
> 
Great! I'm all for outsourcing this to the build script! (do_chroot is a
mess (especially, if you use "su" as a su-wrapper).)

I just had a quick glance at it:
- it'll always login as root (if I get the obs-build code right):
  * what about adding a new "--shell-cmd <cmd>" option to obs-build? Then,
    osc simply passes "--shell-cmd 'su - abuild'" and we have the old behavior
    (this way, we can easily support the existing --login-as-root option, too)
- --wipe is currently not supported => breaks UI (but this can be easily
  fixed)
- there is no dedicated entry for "chroot" in "osc --help" anymore (it is part
  of the "build" help text). But I can live with that:) (maybe we could mention
  the chroot command in do_build's __docstr__)

**Comment by adrianschroeter** [comment]
Finally had time for it again:

> - it'll always login as root (if I get the obs-build code right):
>  * what about adding a new "--shell-cmd <cmd>" option to obs-build? Then,
>    osc simply passes "--shell-cmd 'su - abuild'" and we have the old behavior
>    (this way, we can easily support the existing --login-as-root option, too)

I have implemented the --shell-cmd option in obs-build and osc now. However, I am 
actually unsure atm if I really want to add the option for "--login-as-root" in osc here,
because it is something the build script should do and not osc.

Atm I made sure that the user gets informed that he is root and give the CLI he
needs to switch to the right user (also something what build script would deside).

I would leave that as incompability atm and wait for feedback...

> - --wipe is currently not supported => breaks UI (but this can be easily  fixed)

also supported build script now.

> - there is no dedicated entry for "chroot" in "osc --help" anymore (it is part
>   of the "build" help text). But I can live with that:) (maybe we could mention
>   the chroot command in do_build's __docstr__)

this is actually wanted, since it is just the for compability, but it should not be documented
anymore. It would just made the already large help section more crowded.

**Comment by adrianschroeter** [comment]
of course you need again the build script version from the morning again for this code.

**Comment by lethliel** [comment]
Looks good now

**Pull request merged**
