### PR TITLE
VM build fixes

### PR DESCRIPTION
**Pull request by adrianschroeter**

### CODE REVIEW

**Comment by adrianschroeter** [comment]
@mlschroe The prjconf line would be

Substitute: cli_debug_packages gdb strace vim ....

does this sound okay or shall we use a different string?

**Comment by adrianschroeter** [comment]
we should maybe use "obs:cli_debug_packages" instead to avoid a theoretically conflict with real package named "cli_debug_packages"

**Comment by adrianschroeter** [comment]
On Mittwoch, 4. Dezember 2019, 14:50:36 CET Marco Strigl wrote:
> lethliel requested changes on this pull request.
> 
> In oscrc no_verify is used. See commandline.py line 6466:
> 
> ```
> if conf.config['no_verify']:
>             opts.no_verify = True
> ```

okay, dropped that commit here for now.

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by lethliel** [comment]
This looks good and should work (As far as I can see) 

In a further step we need to:

- normalize no-verify option
- clean up build.py

Thanks for the effort and the patch

**Comment by nickbroon** [comment]
@adrianschroeter @lethliel 
This is resulting in:
```
  File "/usr/lib/python2.7/dist-packages/osc/build.py", line 1298, in main
    osc.core.store_write_last_buildroot(os.curdir, repo, arch, vm_type)
  File "/usr/lib/python2.7/dist-packages/osc/core.py", line 6549, in store_write_last_buildroot
    store_write_string(dir, '_last_buildroot', repo + '\n' + arch + '\n' + vm_type + '\n')
  File "/usr/lib/python2.7/dist-packages/osc/core.py", line 6531, in store_write_string
    f = open(fname + '.new', 'w')
IOError: [Errno 2] No such file or directory: './.osc/_last_buildroot.new'
```

commenting out line 1298 in /usr/lib/python2.7/dist-packages/osc/build.py seems to get things moving:  `# osc.core.store_write_last_buildroot(os.curdir, repo, arch, vm_type)`

**Comment by marcus-h** [comment]
On 2019-12-06 03:40:07 -0800, Nick Brown wrote:
> @adrianschroeter @lethliel
> This is resulting in:
> ```
>   File "/usr/lib/python2.7/dist-packages/osc/build.py", line 1298, in main
>     osc.core.store_write_last_buildroot(os.curdir, repo, arch, vm_type)
>   File "/usr/lib/python2.7/dist-packages/osc/core.py", line 6549, in store_write_last_buildroot
>     store_write_string(dir, '_last_buildroot', repo + '\n' + arch + '\n' + vm_type + '\n')
>   File "/usr/lib/python2.7/dist-packages/osc/core.py", line 6531, in store_write_string
>     f = open(fname + '.new', 'w')
> IOError: [Errno 2] No such file or directory: './.osc/_last_buildroot.new'
> ```
>
> commenting out line 1298 in /usr/lib/python2.7/dist-packages/osc/build.py seems to get things moving:  `# osc.core.store_write_last_buildroot(os.curdir, repo, arch, vm_type)`
>
We should only do this in case of a package working copy:

if is_package_dir(os.curdir):
    ...

so that we still support the no package working copy use/special case
(which only works if no _service file exists).

**Comment by lethliel** [comment]
Jupp. You are right. Will implement this. 

Anyhow. 

@nickbroon Can you please provide the command you are issuing? Just to be sure we don't miss further corner cases

**Comment by nickbroon** [comment]
`osc --download-api-only --local-package --no-service --trust-all-projects --build-uid=caller --alternative-project=RELEASE:FOO standard`

**Comment by lethliel** [comment]
No. It is fine. I will fix it without an issue as this is clearly a bug.

**Pull request merged**
