### PR TITLE
Support flatpak building

### PR DESCRIPTION
**Pull request by mlschroe**

### CODE REVIEW

**Comment by marcus-h** [comment]
On 2020-11-11 09:06:21 -0800, Michael Schroeder wrote:
> diff --git a/osc/commandline.py b/osc/commandline.py
> index 5ebcaf6e..7f42e0bb 100644
> --- a/osc/commandline.py
> +++ b/osc/commandline.py
> @@ -6245,7 +6245,7 @@ def parse_repoarchdescr(self, args, noinit = False, alternative_project = None,
>                  for subarch in osc.build.can_also_build.get(mainarch):
>                      all_archs.append(subarch)
>              for arg in args:
> -                if arg.endswith('.spec') or arg.endswith('.dsc') or arg.endswith('.kiwi') or arg.endswith('.livebuild') or arg == 'PKGBUILD' or arg == 'build.collax' or arg == 'Dockerfile' or arg == 'fissile.yml' or arg == 'appimage.yml':
> +                if arg.endswith('.spec') or arg.endswith('.dsc') or arg.endswith('.kiwi') or arg.endswith('.livebuild') or arg == 'PKGBUILD' or arg == 'build.collax' or arg == 'Dockerfile' or arg == 'fissile.yml' or arg == 'appimage.yml' or arg.endswith('flatpak.yaml') or arg.endswith('flatpak.yml' or arg.endswith('flatpak.json')):

There's a ")" missing after 'flatpak.yml'. That is,
arg.endswith('flatpak.yml') or arg.endswith('flatpak.json'):

Otherwise, LGTM!

**Comment by mlschroe** [comment]
Yeah, copy-n-paste programming at its finest. Thanks for spotting this. Force pushed.

**Comment by mlschroe** [comment]
Reopening...

**Comment by marcus-h** [comment]
Merged. Thanks a lot!

**Pull request merged**
