### PR TITLE
integrated comments command

### PR DESCRIPTION
**Pull request by lethliel**
added comments subcommand to osc: 

### List comments:

```
osc comment list package PROJECT PACKAGE
osc comment list project PROJECT 
osc comment list request ID
```

### create comment:

```
osc comment create package PROJECT PACKAGE 'COMMENT' [-p parent_id]
osc comment create project PROJECT 'COMMENT' [-p parent_id]
osc comment create request ID 'COMMENT' [-p parent_id]
```

### delete comment

``` 
osc delete comment ID
```

This PR needs this to be merged before it works: https://github.com/openSUSE/open-build-service/pull/2722
This is for issue #250

### CODE REVIEW

**Comment by marcus-h** [comment]
On 2017-03-02 06:58:04 -0800, Marco Strigl wrote:
> ### create comment:
> 
> osc comment create package PROJECT PACKAGE 'COMMENT' [-p parent_id]
> osc comment create project PROJECT 'COMMENT' [-p parent_id]
> osc comment create request ID 'COMMENT' [-p parent_id]

Hmm what about making the comment parameter optional? That is, if the
comment is omitted, $EDITOR is opened and the user can enter the comment.

Some minor comments below.

> diff --git a/osc/commandline.py b/osc/commandline.py
> index 4b01f7d..b5a7b32 100644
> --- a/osc/commandline.py
> +++ b/osc/commandline.py
> @@ -2353,7 +2353,7 @@ Please submit there instead, or use --nodevelproject to force direct submission.
>                                                    source_buildstatus=source_buildstatus)
>              else:
>                  print(r)
> -                print_comments(apiurl, 'request', reqid)
> +                print_comments(apiurl, 'request', req=reqid)
>              if source_buildstatus:
>                  sr_actions = r.get_actions('submit')
>                  if not sr_actions:
> @@ -8737,6 +8737,94 @@ Please submit there instead, or use --nodevelproject to force direct submission.
>                  if not opts.dry_run:
>                      os.unlink(os.path.join(p.absdir, filename))
>  
> +    @cmdln.option('-p', '--parent',
> +                  help='reply to comment with parent id')

Maybe also add a "metavar='PARENT'" argument.

> +    def do_comment(self, subcmd, opts, *args):
> +        """${cmd_name}: List / create / delete comments
> +
> +        On create:
> +            If -p is given a reply to the ID is created. Otherwise
> +            a toplevel comment is created.
> +
> +        usage:
> +            osc comment list package PROJECT PACKAGE
> +            osc comment list project PROJECT
> +            osc comment list request REQUEST_ID
> +
> +            osc comment create [-p PARENT_ID] package PROJECT PACKAGE 'COMMENT'
> +            osc comment create [-p PARENT_ID] project PROJECT 'COMMENT'
> +            osc comment create [-p PARENT_ID] request REQUEST_ID 'COMMENT'
> +
> +            osc comment delete ID
> +
> +        """
> +
> +        project = package = request = comment = parent = None
> +
parent is not needed.

> +        args = slash_split(args)
> +        apiurl = self.get_api_url()
> +
> +        if not args or (len(args) < 2 and args[0] != 'delete'):
> +            raise oscerr.WrongArgs('Incorrect number of arguments.\n\n' \
> +                  + self.get_cmd_help('comment'))
> +
> +        cmds = ['list', 'create', 'delete']
> +        if args[0] not in cmds:
> +            raise oscerr.WrongArgs('Unknown comment action %s. Choose one of %s.' \
> +                                                % (args[0], ', '.join(cmds)))
> +
> +        comment_targets = ['package', 'project', 'request']
> +        if args[0] != 'delete' and args[1] not in comment_targets:
> +            raise oscerr.WrongArgs('Unknown comment target %s. Choose one of %s.' \
> +                                                % (args[1], ', '.join(comment_targets)))
> +
> +        if args[0] == 'list' and args[1] == 'package':
> +            if len(args) != 4:
> +                raise oscerr.WrongArgs('Please use PROJECT PACKAGE')
> +        elif args[0] == 'list' and args[1] == 'project':
> +            if len(args) != 3:
> +                raise oscerr.WrongArgs('Please use PROJECT')
> +        elif args[0] == 'list' and args[1] == 'request':
> +            if len(args) != 3:
> +                raise oscerr.WrongArgs('Please use REQUEST')
> +        elif args[0] == 'create' and args[1] == 'package':
> +            if len(args) != 5:
> +                raise oscerr.WrongArgs('Please use PROJECT PACKAGE COMMENT')
> +        elif args[0] == 'create' and args[1] == 'project':
> +            if len(args) != 4:
> +                raise oscerr.WrongArgs('Please use PROJECT COMMENT')
> +        elif args[0] == 'create' and args[1] == 'request':
> +            if len(args) != 4:
> +                raise oscerr.WrongArgs('Please use REQUEST COMMENT')
> +        elif args[0] == 'delete':
> +            if len(args) != 2:
> +                raise oscerr.WrongArgs('Please use COMMENT_ID')
> +
You can save here a level of indentation: just move the len(args)
check(s) to the previous line(s)

> +        if args[1] == 'package':
> +            project = args[2]
> +            package = args[3]
> +            if args[0] == 'create':
> +                comment = args[4]
> +        elif args[1] == 'project':
> +            project = args[2]
> +            if args[0] == 'create':
> +                comment = args[3]
> +        elif args[1] == 'request':
> +            request = args[2]
> +            if args[0] == 'create':
> +                comment = args[3]
> +
We could avoid these repeated "if args[0] == 'create'" statements, if
we .pop(n) the "consumed" arguments... but the current solution is also
fine...

> +        if args[0] == 'list':
> +            print_comments(apiurl, args[1], proj=project, pkg=package, req=request)
> +        elif args[0] == 'create':
> +            parent = opts.parent
> +            result = create_comment(apiurl, args[1], comment,
> +                                    proj=project, pkg=package, req=request, parent=parent)

Just write parent=opt.parent

> +            print(result)
> +        elif args[0] == 'delete':
> +            result = delete_comment(apiurl, args[1])
> +            print(result)
> +
>      def _load_plugins(self):
>          plugin_dirs = [
>              '/usr/lib/osc-plugins',
> diff --git a/osc/core.py b/osc/core.py
> index 3242bce..ae34a27 100644
> --- a/osc/core.py
> +++ b/osc/core.py
> @@ -7407,26 +7407,56 @@ def which(name):
>      return None
>  
>  
> -def get_comments(apiurl, kind, name):
> -    url = makeurl(apiurl, ['comments', kind, name])
> +def get_comments(url):
>      f = http_GET(url)
>      return ET.parse(f).getroot()
>  
Hmm the url building logic belongs to this function and shouldn't
be the task of the caller. For instance, something like this

def get_comments(apiurl, kind, *args):
    url = makeurl(apiurl, ('comments', kind) + args)
    f = http_GET(url)
    return ET.parse(f).getroot()


> -def print_comments(apiurl, kind, name):
> +def print_comments(apiurl, kind, proj=None, pkg=None, req=None):
>      def print_rec(comments, indent=''):
>          for comment in comments:
>              print(indent, end='')
> -            print('On', comment.get('when'), comment.get('who'), 'wrote:')
> +            print('(', comment.get('id'), ')', 'On', comment.get('when'), comment.get('who'), 'wrote:')
>              text = indent + comment.text.replace('\r\n',' \n')
>              print(('\n' + indent).join(text.split('\n')))
>              print()
>              print_rec([c for c in root if c.get('parent') == comment.get('id')], indent + '  ')
> -
> -    root = get_comments(apiurl, kind, name)
> +    if kind == 'package':
> +        url = makeurl(apiurl, ['comments', kind, proj, pkg])
> +    elif kind == 'project':
> +        url = makeurl(apiurl, ['comments', kind, proj])
> +    elif kind == 'request':
> +        url = makeurl(apiurl, ['comments', kind, req])

See above.

> +    root = get_comments(url)
>      comments = [c for c in root if c.get('parent') is None]
>      if comments:
>          print('\nComments:')
>          print_rec(comments)
>  
> +def create_comment(apiurl, kind, comment, proj=None, pkg=None, req=None, parent=None):
> +    makeargs = ['comments', kind]
> +    if kind == 'package':
> +        makeargs.extend((proj, pkg))
> +    elif kind == 'project':
> +        makeargs.append(proj)
> +    elif kind == 'request':
> +        makeargs.append(req)
> +
Hmm we could also simplify this (see above):

def create_comment(apiurl, kind, parent=None, *args):
    ...

but that's up to you:) (it should be be consistent with get_comments)

> +    query = {}
> +    if parent is not None:
> +        print("Here")

Debug code:)

> +        query = {'parent_id': parent}
> +
> +    u = makeurl(apiurl, makeargs, query=query)
> +
> +    f = http_POST(u, data=comment)
> +    ret = ET.fromstring(f.read()).find('summary')
> +    return (ret.text)
> +
Parentheses can be omitted.

> +def delete_comment(apiurl, cid):
> +    u = makeurl(apiurl, ['comment', cid])
> +    f = http_DELETE(u)
> +    ret = ET.fromstring(f.read()).find('summary')
> +    return (ret.text)
> +
Parentheses can be omitted.

**Comment by lethliel** [comment]
- changed syntax of call: 
`osc comment create <kind> [-c COMMENT] [-p PARENTID] PROJECT PACKAGE || REQ`
- if `-c` is not given the default editor is opened and you can enter the comment
- simplified args and opts checking in commandline.py
- moved url generation to right function and simplified function calls. 
- removed debug code :-)

**Comment by lethliel** [comment]
added auto-completion for osc comment command

**Comment by marcus-h** [comment]
On 2017-03-06 06:12:09 -0800, Marco Strigl wrote:
> - changed syntax of call: 
> `osc comment create <kind> [-c COMMENT] [-p PARENTID] PROJECT PACKAGE || REQ`
> - if `-c` is not given the default editor is opened and you can enter the comment

Sounds good.

> - simplified args and opts checking in commandline.py
> - moved url generation to right function and simplified function calls. 

Ok. Thanks.

> - removed debug code :-)
> 
And added new debug code;)

A few minor comments below.

> diff --git a/osc/commandline.py b/osc/commandline.py
> index 4b01f7d..10a1289 100644
> --- a/osc/commandline.py
> +++ b/osc/commandline.py
> @@ -2353,7 +2353,7 @@ Please submit there instead, or use --nodevelproject to force direct submission.
>                                                    source_buildstatus=source_buildstatus)
>              else:
>                  print(r)
> -                print_comments(apiurl, 'request', reqid)
> +                print_comments(apiurl, 'request', req=reqid)

print_comments(apiurl, 'request', reqid)
(see below)

>              if source_buildstatus:
>                  sr_actions = r.get_actions('submit')
>                  if not sr_actions:
> @@ -8737,6 +8737,82 @@ Please submit there instead, or use --nodevelproject to force direct submission.
>                  if not opts.dry_run:
>                      os.unlink(os.path.join(p.absdir, filename))

<SNIP>

> +        project = package = request = comment = None
> +
We can get rid of project, package, and request (see below).

> +        args = slash_split(args)
> +        apiurl = self.get_api_url()
> +
> +        if not args or (len(args) < 2 and args[0] != 'delete'):
> +            raise oscerr.WrongArgs('Incorrect number of arguments.\n\n' \
> +                  + self.get_cmd_help('comment'))
> +
We should simply check for "if len(args) < 2" (len(args) < 2 is also an
error in the "delete" case).

> +        if args[1] == 'package':
> +            project = args[2]
> +            package = args[3]
> +        elif args[1] == 'project':
> +            project = args[2]
> +        elif args[1] == 'request':
> +            request = args[2]
> +
This code can be removed.

> +        if args[0] == 'list':
> +            print_comments(apiurl, args[1], proj=project, pkg=package, req=request)

print_comments(apiurl, *args[1:])
(see below)

> +        elif args[0] == 'create':
> +            result = create_comment(apiurl, args[1], comment,
> +                                    project, package, request, parent=opts.parent)

result = create_comment(apiurl, args[1], comment, *args[2:],
                        parent=opts.parent)
(see below)

> +            print(result)

> index 3242bce..453bdb8 100644
> --- a/osc/core.py
> +++ b/osc/core.py
> @@ -7407,26 +7407,43 @@ def which(name):
>      return None
>  
>  
> -def get_comments(apiurl, kind, name):
> -    url = makeurl(apiurl, ['comments', kind, name])
> +def get_comments(apiurl, kind, *args):
> +    args = filter(None, args)

With the change from above, the filter is not needed anymore.

> +    url = makeurl(apiurl, ('comments', kind) + args)
> +    print(url)

Debug code:)

<SNIP>

> -def print_comments(apiurl, kind, name):
> +def print_comments(apiurl, kind, proj=None, pkg=None, req=None):

def print_comments(apiurl, kind, *args):

This makes the interface a bit "nicer" and more "general".

>      def print_rec(comments, indent=''):
>          for comment in comments:
>              print(indent, end='')
> -            print('On', comment.get('when'), comment.get('who'), 'wrote:')
> +            print('(', comment.get('id'), ')', 'On', comment.get('when'), comment.get('who'), 'wrote:')
>              text = indent + comment.text.replace('\r\n',' \n')
>              print(('\n' + indent).join(text.split('\n')))
>              print()
>              print_rec([c for c in root if c.get('parent') == comment.get('id')], indent + '  ')
> -
> -    root = get_comments(apiurl, kind, name)
> +    root = get_comments(apiurl, kind, proj, pkg, req)

root = get_comments(apiurl, kind, *args)
(see above)

>      comments = [c for c in root if c.get('parent') is None]
>      if comments:
>          print('\nComments:')
>          print_rec(comments)
>  
> +def create_comment(apiurl, kind, comment, *args, **kwargs):

(We could swap the positions of "kind" and "comment" in order to
further simplify the previous code...)

> +    args = filter(None, args)

See above.

> +    query = {}
> +    if kwargs['parent'] is not None:

Using kwargs.get('parent') is more "safe" and appropriate, because
parent is supposed to be optional (the current implementation makes
it a mandatory argument)

**Comment by lethliel** [comment]
- removed debug code (and hopefully not added new one)
- simplified argument handling and function calls

**Comment by marcus-h** [comment]
On 2017-03-06 07:31:08 -0800, Marco Strigl wrote:
> - removed debug code (and hopefully not added new one)
> - simplified argument handling and function calls
> 
Almost perfect:)

> diff --git a/osc/commandline.py b/osc/commandline.py
> index 4b01f7d..54b1a36 100644
> --- a/osc/commandline.py
> +++ b/osc/commandline.py
> +
> +        comment = None
> +        args = slash_split(args)
> +        apiurl = self.get_api_url()
> +
> +        if not args or (len(args) < 2):

Just "if len(args) < 2:"

> diff --git a/osc/core.py b/osc/core.py
> index 3242bce..fbe9b10 100644
> --- a/osc/core.py
> +++ b/osc/core.py
> @@ -7407,26 +7407,39 @@ def which(name):
>      return None
>  
>  
> -def get_comments(apiurl, kind, name):
> -    url = makeurl(apiurl, ['comments', kind, name])
> +def get_comments(apiurl, kind, *args):

The makeurl call is gone.

>      f = http_GET(url)
>      return ET.parse(f).getroot()
>  
>  
> -def print_comments(apiurl, kind, name):
> +def print_comments(apiurl, kind, *args):
>      def print_rec(comments, indent=''):
>          for comment in comments:
>              print(indent, end='')
> -            print('On', comment.get('when'), comment.get('who'), 'wrote:')
> +            print('(', comment.get('id'), ')', 'On', comment.get('when'), comment.get('who'), 'wrote:')
>              text = indent + comment.text.replace('\r\n',' \n')
>              print(('\n' + indent).join(text.split('\n')))
>              print()
>              print_rec([c for c in root if c.get('parent') == comment.get('id')], indent + '  ')
> -
> -    root = get_comments(apiurl, kind, name)
> +    root = get_comments(apiurl, kind, *args)
>      comments = [c for c in root if c.get('parent') is None]
>      if comments:
>          print('\nComments:')
>          print_rec(comments)
>  
> +def create_comment(apiurl, kind, comment, *args, **kwargs):
> +    query = {}
> +    if kwargs['parent'] is not None:

It is important to use kwargs.get('parent') here (if parent was
not passed, a KeyError is raised)

> +        query = {'parent_id': kwargs.get('parent')}

(Using kwargs['parent'] here is safe)

**Comment by lethliel** [comment]
On 03/06/2017 04:55 PM, Marcus Hüwe wrote:
> On 2017-03-06 07:31:08 -0800, Marco Strigl wrote:
>> - removed debug code (and hopefully not added new one)
>> - simplified argument handling and function calls
>>
> Almost perfect:)
> 

<SNIP>

Oops. I didn't recognize the parentheses around the or statement. (old perl habit i guess) 
And reinserted the makeurl call. I should not code If i am tired :) 


>>
>> +def create_comment(apiurl, kind, comment, *args, **kwargs):
>> + query = {}
>> + if kwargs['parent'] is not None:
> 
> It is important to use kwargs.get('parent') here (if parent was
> not passed, a KeyError is raised)
> 
>> + query = {'parent_id': kwargs.get('parent')}
> 
> (Using kwargs['parent'] here is safe)
> 

I changed the two now. And i get your point. But if I call the command without 
the parent no error is raised at all. Could it be python version specific?

**Comment by marcus-h** [comment]
On 2017-03-06 08:08:58 -0800, Marco Strigl wrote:
> On 03/06/2017 04:55 PM, Marcus Hüwe wrote:
> > On 2017-03-06 07:31:08 -0800, Marco Strigl wrote:
> >> - removed debug code (and hopefully not added new one)
> >> - simplified argument handling and function calls
> >>
> > Almost perfect:)
> > 
> 
> <SNIP>
> 
> Oops. I didn't recognize the parentheses around the or statement. (old perl habit i guess) 
> And reinserted the makeurl call. I should not code If i am tired :) 
> 
Hmm I actually meant "if len(args) < 2:" instead of
"if not args or len(args) < 2" (since "not args" implies
"len(args) < 2").

> 
> >>
> >> +def create_comment(apiurl, kind, comment, *args, **kwargs):
> >> + query = {}
> >> + if kwargs['parent'] is not None:
> > 
> > It is important to use kwargs.get('parent') here (if parent was
> > not passed, a KeyError is raised)
> > 
> >> + query = {'parent_id': kwargs.get('parent')}
> > 
> > (Using kwargs['parent'] here is safe)
> > 
> 
> I changed the two now. And i get your point. But if I call the command without 
> the parent no error is raised at all. Could it be python version specific? 
> 
As I said this is just for "future" callers: for instance

    create_comment(apiurl, 'request', comment, '1234')

would result in a KeyError (with the old code).

**Comment by lethliel** [comment]
@marcus-h I hope this time i got everything

**Comment by marcus-h** [comment]
LGTM. Merged. Thanks!

**Pull request merged**
