### PR TITLE
Support parameters on token triggers

### PR DESCRIPTION
**Pull request by adrianschroeter**
Add missing parameters for token triggers. Esp used for rebuild and release commands.

### CODE REVIEW

**Comment by adrianschroeter** [comment]
@dirkmueller please test

**Comment by dmach** [comment]
I have simplified `url_query`.
`makeurl()` is now smart and skips items with value that equals `None`.

Also, I fixed the `set_release_to` error reported by pylint.

**Comment by dmach** [comment]
One more change: `--repo` and `--arch` seem to be widely used in osc so I used those instead of `--repository` and --architecture`. I also replaced `--target-repository` with `--target-repo` to be consistent.

**Comment by adrianschroeter** [comment]
okay, cool
and I just changed one more thing, using "repository" instead of "filter_source_repository" as the api is going to be fixed here now as well (the three options made no sense and were not working properly there).

**Pull request merged**
