### PR TITLE
add meta group function to edit / show group meta

### PR DESCRIPTION
**Pull request by lethliel**
show and edit group meta: 

```
osc meta group <mygroup>
osc meta group -e <mygroup>
```

### CODE REVIEW

**Comment by lethliel** [comment]
@marcus-h: please review. Thanks.

**Comment by marcus-h** [comment]
LGTM, except that "get_group_meta" does the same as "get_group". The
latter is actually a "misnomer":/ Can you either change your code
to use "get_group" or simply call "get_group" in "get_group_meta"?

A "funny" side node:

> +            elif cmd == 'group':
> +                edit_meta(metatype='group',
> +                          edit=True,
> +                          path_args=(quote_plus(group)),
> +                          apiurl=apiurl,
> +                          template_args=({'group': group}))

Actually, I should yell "superfluous parentheses" again, but all the
surrounding code does the same:/

**Comment by lethliel** [comment]
@marcus-h 

Ok. I was not aware of the existing get_group function. 

The superfluous parentheses are everywehe :-)

**Comment by marcus-h** [comment]
On 2017-08-18 13:33:48 +0000, Marco Strigl wrote:
> Ok. I was not aware of the existing get_group function. 
> 
Merged. Thanks!

> The superfluous parentheses are everywehe :-) 
> 
;)

**Pull request merged**
