### PR TITLE
Honor XDG_CONFIG_HOME and XDG_CACHE_HOME env vars

### PR DESCRIPTION
**Pull request by dmach**
Fixes: #1481

### CODE REVIEW

**Comment by dmach** [comment]
@Thaodan could you test if the patch works for you?

**Comment by Thaodan** [comment]
Daniel Mach ***@***.***> writes:

> @Thaodan could you test if the patch works for you?

The patch works for me, the trusted certs folder is created in
XDG_CONFIG_HOME now.
However I'm not sure if that's the right place for the folder as it's
more part of the state as opposed to config.

When accepting projects as trusted the change isn't written to oscrc.
n

**Comment by dmach** [comment]
> When accepting projects as trusted the change isn't written to oscrc.

The original report was about trusted **certs**.
Now you're writing about trusted **projects**. Is this what you really meant?
I just want to make clear that you didn't write it by an accident and that there might be an additional bug.

**Comment by Thaodan** [comment]
> > When accepting projects as trusted the change isn't written to oscrc.
> 
> The original report was about trusted **certs**. Now you're writing about trusted **projects**. Is this what you really meant? I just want to make clear that you didn't write it by an accident and that there might be an additional bug.

The original report was also about the trusted projects:

> In addition it doesn't save options such as the permanent saving of trusted project to oscrc when $XDG_CONFIG_HOME is set.

**Comment by dmach** [comment]
> The original report was also about the trusted projects:

I did not think that this is even possible, but clearly is.
I've updated this PR with a new commit that warns you if you have `~/.oscrc` on disk, because that ignores `XDG_CONFIG_HOME`  and `~/.config/osc/oscrc`.
Isn't that your case?
It would use the trusted projects from the existing `~/.oscrc` and storing new values there.

If you don't have `~/.oscrc` on disk, then I'm afraid I have no idea what's wrong with the trusted projects, everything worked fine for me when I tested this.

**Comment by Thaodan** [comment]
Daniel Mach ***@***.***> writes:

>> The original report was also about the trusted projects:
>
> I did not think that this is even possible, but clearly is.
> I've updated this PR with a new commit that warns you if you have
> `~/.oscrc` on disk, because that ignores `XDG_CONFIG_HOME` and
> `~/.config/osc/oscrc`.
> Isn't that your case?
> It would use the trusted projects from the existing `~/.oscrc` and storing new values there.
>
> If you don't have `~/.oscrc` on disk, then I'm afraid I have no idea
> what's wrong with the trusted projects, everything worked fine for me
> when I tested this.

No my case is to have $XDG_CONFIG_HOME set to $HOME/.local/etc.
However I forgot to mention that oscrc is symlink to
$HOME/.local/private/etc/osc/oscrc.
The purpose of this is to separate my osc config as it can contain
confidential data.

**Comment by dmach** [comment]
The symlinks seem to be the root cause after all.
I was able to reproduce not storing the trusted projects into a symlinked config, adding `osc.path.realpath()` fixed that for me.

**Comment by Thaodan** [comment]
Thank you for fixing the bug.

**Pull request merged**
