### PR TITLE
implement osc build --shell-after-fail

### PR DESCRIPTION
**Pull request by adrianschroeter**

### CODE REVIEW

**Comment by marcus-h** [comment]
On 2021-02-11 02:01:39 -0800, Adrian Schröter wrote:
> diff --git a/osc/build.py b/osc/build.py
> index 9b040a9c..86dfa748 100644
> --- a/osc/build.py
> +++ b/osc/build.py
> @@ -571,6 +571,7 @@ def main(apiurl, opts, argv):
>      build_root = None
>      cache_dir  = None
>      build_uid = ''
> +    shell_after_fail = config['shell-after-fail']

If the config option is not set, this results in a KeyError. We
should add the corresponding boolean option to the conf module.
Maybe we should call it "build-shell-after-fail"?.

>      vm_memory = config['build-memory']
>      vm_disk_size = config['build-vmdisk-rootsize']
>      vm_type = config['build-type']
> @@ -665,6 +666,8 @@ def main(apiurl, opts, argv):
>          else:
>              print('Error: build-uid arg must be 2 colon separated numerics: "uid:gid" or "caller"', file=sys.stderr)
>              return 1
> +    if opts.shell_after_fail:
> +        shell_after_fail = opts.shell_after_fail
>      if opts.vm_memory:
>          vm_memory = opts.vm_memory
>      if opts.vm_disk_size:
> @@ -740,6 +743,9 @@ def main(apiurl, opts, argv):
>      if opts.shell:
>          buildargs.append("--shell")
>
> +    if shell_after_fail:
> +        buildargs.append("--shell-after-fail")
> +
>      if opts.shell_cmd:
>          buildargs.append("--shell-cmd")
>          buildargs.append(opts.shell_cmd)
> diff --git a/osc/commandline.py b/osc/commandline.py
> index 162de1eb..09d5ea37 100644
> --- a/osc/commandline.py
> +++ b/osc/commandline.py
> @@ -771,7 +771,7 @@ def do_showlinked(self, subcmd, opts, *args):
>      @cmdln.option('-d', '--delete', metavar='TOKENID',
>                          help='Delete a token')
>      @cmdln.option('-o', '--operation', metavar='OPERATION',
> -                        help='Default is "runservice", but "release" or "rebuild" can also be used')
> +                        help='Default is "runservice", but "branch", "release" or "rebuild" can also be used')

Hmm unrelated (but OK...).

>      @cmdln.option('-t', '--trigger', metavar='TOKENSTRING',
>                          help='Trigger the action of a token')
>      def do_token(self, subcmd, opts, *args):
> @@ -6512,6 +6512,8 @@ def parse_repoarchdescr(self, args, noinit = False, alternative_project = None,
>                    help=SUPPRESS_HELP)
>      @cmdln.option('--shell', action='store_true',
>                    help=SUPPRESS_HELP)
> +    @cmdln.option('--shell-after-fail', action='store_true',
> +                  help="runing a shell if the build tool fails")

s/runing/running/
Maybe "run a shell if the build fails" (or failed?)?

**Comment by adrianschroeter** [comment]
On Donnerstag, 11. Februar 2021, 13:24:52 CET Marcus Hüwe wrote:
> On 2021-02-11 02:01:39 -0800, Adrian Schröter wrote:
> > diff --git a/osc/build.py b/osc/build.py
> > index 9b040a9c..86dfa748 100644
> > --- a/osc/build.py
> > +++ b/osc/build.py
> > @@ -571,6 +571,7 @@ def main(apiurl, opts, argv):
> >      build_root = None
> >      cache_dir  = None
> >      build_uid = ''
> > +    shell_after_fail = config['shell-after-fail']
> 
> If the config option is not set, this results in a KeyError. We
> should add the corresponding boolean option to the conf module.
> Maybe we should call it "build-shell-after-fail"?.

k, renamed and added.

...

> >      @cmdln.option('-t', '--trigger', metavar='TOKENSTRING',
> >                          help='Trigger the action of a token')
> >      def do_token(self, subcmd, opts, *args):
> > @@ -6512,6 +6512,8 @@ def parse_repoarchdescr(self, args, noinit = False, alternative_project = None,
> >                    help=SUPPRESS_HELP)
> >      @cmdln.option('--shell', action='store_true',
> >                    help=SUPPRESS_HELP)
> > +    @cmdln.option('--shell-after-fail', action='store_true',
> > +                  help="runing a shell if the build tool fails")
> 
> s/runing/running/
> Maybe "run a shell if the build fails" (or failed?)?

changed it a bit, but I mentioned the build tool, because it does not
happen when other things fail, like rpmlint failures.

I am not sure if this actually a good behaviour, but it is the current one.

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by marcus-h** [comment]
On 2021-02-11 04:33:39 -0800, Adrian Schröter wrote:

...

> diff --git a/osc/conf.py b/osc/conf.py
> index d0cf6869..2300a908 100644
> --- a/osc/conf.py
> +++ b/osc/conf.py
> @@ -108,6 +108,7 @@ def _get_processors():
>              'build-uid': '',                    # use the default provided by build
>              'build-device': '',                 # required for VM builds
>              'build-memory': '',                 # required for VM builds
> +            'build-shell-after-fail': '',       # optional for VM builds

Hmm let's use

'build-shell-after-fail': '0',

and then add

"build-shell-after-fail" to the "boolean_opts" list.

Otherwise, LGTM:)

**Comment by marcus-h** [comment]
On 2021-02-11 04:33:39 -0800, Adrian Schröter wrote:
> On Donnerstag, 11. Februar 2021, 13:24:52 CET Marcus Hüwe wrote:
> > On 2021-02-11 02:01:39 -0800, Adrian Schröter wrote:
> > > diff --git a/osc/build.py b/osc/build.py
> > > index 9b040a9c..86dfa748 100644
> > > --- a/osc/build.py
> > > +++ b/osc/build.py
> > > @@ -571,6 +571,7 @@ def main(apiurl, opts, argv):
> > >      build_root = None
> > >      cache_dir  = None
> > >      build_uid = ''
> > > +    shell_after_fail = config['shell-after-fail']
> >
> > If the config option is not set, this results in a KeyError. We
> > should add the corresponding boolean option to the conf module.
> > Maybe we should call it "build-shell-after-fail"?.
>
> k, renamed and added.
>
(Side note: I was only "complaining" about the name of the config option,
the local name (shell_after_fail) was OK (IMHO) but I'm fine with the
new one, too:) )

> > >      @cmdln.option('-t', '--trigger', metavar='TOKENSTRING',
> > >                          help='Trigger the action of a token')
> > >      def do_token(self, subcmd, opts, *args):
> > > @@ -6512,6 +6512,8 @@ def parse_repoarchdescr(self, args, noinit = False, alternative_project = None,
> > >                    help=SUPPRESS_HELP)
> > >      @cmdln.option('--shell', action='store_true',
> > >                    help=SUPPRESS_HELP)
> > > +    @cmdln.option('--shell-after-fail', action='store_true',
> > > +                  help="runing a shell if the build tool fails")
> >
> > s/runing/running/
> > Maybe "run a shell if the build fails" (or failed?)?
>
> changed it a bit, but I mentioned the build tool, because it does not
> happen when other things fail, like rpmlint failures.
>
Ah ok...
Hmm at first I thought "build tool" == "the build script". After reading
a bit of the code it seems to be about the "recipe" or the "recipe's build
step" (but I'm not sure if "recipe" is a good term from a user's POV).

> I am not sure if this actually a good behaviour, but it is the current one.
>
Hmm the current implementation seems to be a bit "inconsistent". For
instance,
- appimage: if pkg2appimage fails, no shell is started and the build
  script exits
- dsc: if lintian fails, a shell is started
- spec: if rpmlint fails, no shell is started

But I guess we have to live with (some of) these "inconsistencies":/

**Comment by adrianschroeter** [comment]
On Freitag, 12. Februar 2021, 01:40:55 CET Marcus Hüwe wrote:
> On 2021-02-11 04:33:39 -0800, Adrian Schröter wrote:
> > On Donnerstag, 11. Februar 2021, 13:24:52 CET Marcus Hüwe wrote:
...
> > > s/runing/running/
> > > Maybe "run a shell if the build fails" (or failed?)?
> >
> > changed it a bit, but I mentioned the build tool, because it does not
> > happen when other things fail, like rpmlint failures.
> >
> Ah ok...
> Hmm at first I thought "build tool" == "the build script". After reading
> a bit of the code it seems to be about the "recipe" or the "recipe's build
> step" (but I'm not sure if "recipe" is a good term from a user's POV).
> 
> > I am not sure if this actually a good behaviour, but it is the current one.
> >
> Hmm the current implementation seems to be a bit "inconsistent". For
> instance,
> - appimage: if pkg2appimage fails, no shell is started and the build
>   script exits
> - dsc: if lintian fails, a shell is started
> - spec: if rpmlint fails, no shell is started
> 
> But I guess we have to live with (some of) these "inconsistencies":/

right, no good, needs to be fixed in build script.

I will discuss with some more people if we should include check failures
here or not...

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by adrianschroeter** [comment]
changed as requested

**Pull request merged**
