### PR TITLE
interpretation of string literals in messages

### PR DESCRIPTION
**Pull request by lethliel**
string literals are not interpreted correctly when using `-m "my\ntwo line message"`

fixes https://github.com/openSUSE/osc/issues/801

### CODE REVIEW

**Comment by marcus-h** [comment]
On 2020-06-25 11:50:03 -0700, Marco Strigl wrote:
> string literals are not interpreted correctly when using `osc ci -m &quot;my\ntwo line message&quot;`
>
Hmm there are some places where we do not perform the unicode_escape stuff:
- do_createrequest
- do_requestmaintainership
- do_deleterequest
- do_changedevelrequest
- do_request
- do_createincident

The change in do_submitrequest looks "wrong": in the "is_project_dir" case,
we do not interpret escape characters (while we should). In the "other" case,
we might also interpret escape sequences that are part of a diff (we should
not do that). Just move the "if opts.message: opts.message = ..." code to
the start of the do_submitrequest method.

**Comment by lethliel** [comment]
@marcus-h Yeah. Missed those. 

moved the decoding at the beginning of do_submitrequest.
Also in do_request.

**Comment by marcus-h** [comment]
On 2020-06-26 01:00:03 -0700, Marco Strigl wrote:
> @marcus-h Yeah. Missed those.
>
do_createincident is still missing:)

**Comment by lethliel** [comment]
@marcus-h *args* Now done

**Comment by marcus-h** [comment]
On 2020-06-26 15:51:52 +0000, Marco Strigl wrote:
> @marcus-h *args* Now done
>
Merged. Thanks!

**Pull request merged**
