### PR TITLE
fix building for "local" arch

### PR DESCRIPTION
**Pull request by adrianschroeter**

### CODE REVIEW

**Comment by mlschroe** [comment]
I think the buildinfo should contain a correct 'repoarch' element for the 'local' packages.

**Comment by mlschroe** [comment]
OTOH maybe osc should not request the buildinfo for arch 'local'?

**Comment by adrianschroeter** [comment]
On Dienstag, 3. Dezember 2019, 13:50:28 CET Michael Schroeder wrote:
> OTOH maybe osc should not request the buildinfo for arch 'local'?

The problem is that "x86_64" itself might not be part of the repository
definition.

So, we would need to map local -> $local_arch on the server side.

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by mlschroe** [comment]
The problem is that '$local_arch' might not match your system.

**Comment by adrianschroeter** [comment]
On Dienstag, 3. Dezember 2019, 14:37:41 CET Michael Schroeder wrote:
> The problem is that '$local_arch' might not match your system.

yes ... also not the case with my solution proposed here, but we could
at least cover this in osc by checking local arch.

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by adrianschroeter** [comment]
okay, mlschroe will solve this on the repo server side to support building against "local" arch. No need for this patch anymore.

**Pull request closed without merging**
