### PR TITLE
Fix emoji in messages

### PR DESCRIPTION
**Pull request by dmach**

### CODE REVIEW

**Comment by AdamMajer** [comment]
FWIW, this code is everywhere to check that there is no unicode in the text and then to escape it.

I think the question we should ask here is whether OBS UTF-8 safe?

**Comment by AdamMajer** [comment]
@lethliel

**Comment by coolo** [comment]
OBS is utf-8. The commit reverted came for #816 and is *very* doubtful indeed. I'm all for reverting this.

**Review by coolo — APPROVED** [review]

**Comment by dmach** [comment]
After doing a detailed review of the revert with @eduardoj and the feedback in this PR, I have decided to merge this.

**Pull request merged**
