### PR TITLE
allow implicit branch on maintenance request creation

### PR DESCRIPTION
**Pull request by adrianschroeter**
via --enforce-branching option

This may be default by server side settings

### CODE REVIEW

**Comment by marcus-h** [comment]
On 2019-07-22 06:35:08 -0700, Adrian Schröter wrote:
> diff --git a/osc/commandline.py b/osc/commandline.py
> index 94c2c7d2..06b330e8 100644
> --- a/osc/commandline.py
> +++ b/osc/commandline.py
> @@ -3182,6 +3182,8 @@ def do_createincident(self, subcmd, opts, *args):
>                          help='specify message TEXT')
>      @cmdln.option('--release-project', metavar='RELEASEPROJECT',
>                          help='Specify the release project')
> +    @cmdln.option('--enforce-branching', action='store_true',
> +                  help='submit from a fresh branched project')
>      @cmdln.option('--no-cleanup', action='store_true',
>                    help='do not remove source project on accept')
>      @cmdln.option('--cleanup', action='store_true',
> @@ -3283,7 +3285,8 @@ def do_maintenancerequest(self, subcmd, opts, *args):
>                                                                   target_project,
>                                                                   None) # unspecified release project
>
> -        r = create_maintenance_request(apiurl, source_project, source_packages, target_project, release_project, opt_sourceupdate, opts.message)
> +        print("XXX", opts.enforce_branching)

Debug code?:)

> +        r = create_maintenance_request(apiurl, source_project, source_packages, target_project, release_project, opt_sourceupdate, opts.message, opts.enforce_branching)
>          print(r.reqid)
>
>          if supersede_existing:
> @@ -6261,6 +6264,7 @@ def parse_repoarchdescr(self, args, noinit = False, alternative_project = None,
>                    help='trust packages from all projects')
>      @cmdln.option('--nopreinstallimage', '--no-preinstallimage', action='store_true',
>                    help='Do not use preinstall images for creating the build root.')
> +    @cmdln.alias('localbuild')
>      def do_build(self, subcmd, opts, *args):
>          """${cmd_name}: Build a package on your local machine
>
> @@ -6294,6 +6298,11 @@ def do_build(self, subcmd, opts, *args):
>              osc build [OPTS] BUILD_DESCR (REPOSITORY = build_repository (config option), ARCH = hostarch)
>              osc build [OPTS] (REPOSITORY = build_repository (config option), ARCH = hostarch, BUILD_DESCR is detected automatically)
>
> +        localbuild allows to build a source with being part of any existing project:
> +            osc localbuild [OPTS] PROJECT REPOSITORY ARCH BUILD_DESCR
> +            osc localbuild [OPTS] PROJECT REPOSITORY ARCH
> +            osc localbuild [OPTS] PROJECT REPOSITORY (ARCH = hostarch, BUILD_DESCR is detected automatically)
> +
>          # Note:
>          # Configuration can be overridden by envvars, e.g.
>          # OSC_SU_WRAPPER overrides the setting of su-wrapper.
> @@ -6313,6 +6322,13 @@ def do_build(self, subcmd, opts, *args):
>          if opts.debuginfo and opts.disable_debuginfo:
>              raise oscerr.WrongOptions('osc: --debuginfo and --disable-debuginfo are mutual exclusive')
>
> +        if subcmd == 'localbuild':
> +            opts.noservice = True
> +            opts.alternative_project = args[0]
> +            args = args[1:]
> +            if len(args) < 1:
> +                raise oscerr.WrongArgs('locabuild needs at least a project and repository name')
> +

Unrelated?!

>          if len(args) > 3:
>              raise oscerr.WrongArgs('Too many arguments')
>
> diff --git a/osc/core.py b/osc/core.py
> index 23ca55f6..6e62f685 100644
> --- a/osc/core.py
> +++ b/osc/core.py
> @@ -3045,11 +3045,13 @@ def __str__(self):
>      def __cmp__(self, other):
>          return cmp(int(self.reqid), int(other.reqid))
>
> -    def create(self, apiurl, addrevision=False):
> +    def create(self, apiurl, addrevision=False, enforce_branching=False):
>          """create a new request"""
>          query = {'cmd'    : 'create' }
>          if addrevision:
>              query['addrevision'] = "1"
> +        if enforce_branching:
> +            query['enforce_branching'] = "1"
>          u = makeurl(apiurl, ['request'], query=query)
>          f = http_POST(u, data=self.to_str())
>          root = ET.fromstring(f.read())
> @@ -4175,7 +4177,7 @@ def create_release_request(apiurl, src_project, message=''):
>      return r
>
>  # create a maintenance incident per request
> -def create_maintenance_request(apiurl, src_project, src_packages, tgt_project, tgt_releaseproject, opt_sourceupdate, message=''):
> +def create_maintenance_request(apiurl, src_project, src_packages, tgt_project, tgt_releaseproject, opt_sourceupdate, message='', opt_force_branching=False):
>      import cgi
>      r = Request()
>      if src_packages:
> @@ -4185,7 +4187,8 @@ def create_maintenance_request(apiurl, src_project, src_packages, tgt_project, t
>          r.add_action('maintenance_incident', src_project=src_project, tgt_project=tgt_project, tgt_releaseproject=tgt_releaseproject, opt_sourceupdate = opt_sourceupdate)
>      # XXX: clarify why we need the unicode(...) stuff
>      r.description = cgi.escape(unicode(message, 'utf8'))
> -    r.create(apiurl, addrevision=True)
> +    query = { 'addrevision': True }

query is unused.

> +    r.create(apiurl, addrevision=True, enforce_branching=opt_force_branching)
>      return r
>
>  def create_submit_request(apiurl,
>

**Comment by adrianschroeter** [comment]
bah, sorry, one should not push code from last week between two meetings, while talking on the phone :/

**Comment by marcus-h** [comment]
On 2019-07-22 08:14:57 -0700, Adrian Schröter wrote:
> bah, sorry, one should not push code from last week between two meetings, while talking on the phone :/
>
:)

> @ -4175,7 +4177,7 @@ def create_release_request(apiurl, src_project, message=''):
>      return r
>
>  # create a maintenance incident per request
> -def create_maintenance_request(apiurl, src_project, src_packages, tgt_project, tgt_releaseproject, opt_sourceupdate, message=''):
> +def create_maintenance_request(apiurl, src_project, src_packages, tgt_project, tgt_releaseproject, opt_sourceupdate, message='', opt_force_branching=False):

Hmm maybe we should simply call the parameter "enforce_branching"?
With the opt_* prefix one could get the impression that this stuff
is part of the request xml.

The API part is missing, right?

**Comment by lethliel** [comment]
Looks good now. Thanks.

**Pull request merged**
