### PR TITLE
Fix Python 3.7 support

### PR DESCRIPTION
**Pull request by z3ntu**
See PEP 479

### CODE REVIEW

**Comment by adrianschroeter** [comment]
why the return? just removing the exception would have the same effect, no?

**Comment by z3ntu** [comment]
It's what the PEP says (`If raise StopIteration occurs directly in a generator, simply replace it with return.`)

**Comment by marcus-h** [comment]
On 2018-09-03 22:35:28 -0700, Adrian Schröter wrote:
> why the return? just removing the exception would have the same effect, no?
> 
Yep, that's the preferred solution:)

@z3ntu: since the python3 branch is @lethliel's baby, let's wait
until he is back so that he can merge/review/comment on your PR.

**Comment by nickbroon** [comment]
I would be great to see the python3 branch merged into master soon. What's the state of the python3 port?

**Comment by lethliel** [comment]
@nickbroon I am currently on vacation in Italy. I will be back next week and then there will be progress again..

**Comment by mcepl** [comment]
@lethliel Welcome back from vacations ;) I have been using ``python3`` branch for couple of months without any problems. If not merging outright (which I would prefer, of course), could we at least get the branch rebased on the top the ``master``, please?

**Comment by lethliel** [comment]
@mcepl @nickbroon I am back from vacation and I am working on the python3 port again. 
Before anything else can be merged into the master this PR has to be merged: https://github.com/openSUSE/osc/pull/410

After that I will create the pull requests for each affected module and discuss the changes with Marcus. 

@mcepl: I will merge master into this branch during this week.

**Comment by lethliel** [comment]
And for this PR I would say just remove the returns. (even if PEP suggests them)

**Comment by z3ntu** [comment]
Found the part you mean:

> The return is necessary for a strictly-equivalent translation, though in this particular file, there is no further code, and the return can be omitted.

And updated the PR.

**Comment by lethliel** [comment]
LGTM. Thanks for the contribution.

**Pull request merged**
