### PR TITLE
Add instructions for installing requirements

### PR DESCRIPTION
**Pull request by hayderimran7**
Added how to install the pre-requirements . These are recommended imho because i had several issues related to versioning and openssl settings when installing the requirements from pip. 
Installing from zypper worked like charm after adding the suse oss repo.

### CODE REVIEW

**Comment by marcus-h** [comment]
On 2016-06-22 17:40:54 -0700, Imran Hayder wrote:
> Added how to install the pre-requirements . These are recommended imho because i had several issues related to versioning and openssl settings when installing the requirements from pip. 
> Installing from zypper worked like charm after adding the suse oss repo.

Hmm why do you need the curl stuff? Installing python-urlgrabber and
python-M2Crypto (which is actually optional) should be sufficient.

**Comment by hayderimran7** [comment]
@marcus-h `libcurl4` is needed of python-pycurl

**Comment by marcus-h** [comment]
On 2016-06-23 14:33:56 -0700, Imran Hayder wrote:
> @marcus-h `libcurl4` is needed of python-pycurl
> 
Yes, python-pycurl is required by python-urlgrabber. Installing
python-urlgrabber via zypper will automatically install python-pycurl
etc. (at least on a recent Tumbleweed installation).

What concrete problem did you face?

**Comment by lethliel** [comment]
This is now very old. There is no python-urlgrabber anymore and this should no longer be a problem with newer distributions.

**Pull request closed without merging**
