### PR TITLE
honor rev when creating maintenance incident

### PR DESCRIPTION
**Pull request by lethliel**
When creating a submit reqeust against a project that does not
accept SR anymore a maintenance request via create_maintenance_request
is generated. With this commit the orev will be honored and the
appropriate revision will be submitted.

### CODE REVIEW

**Comment by lethliel** [comment]
@marcus-h 
Happy new year and please review :-)

**Comment by marcus-h** [comment]
On 2020-01-08 06:40:55 -0800, Marco Strigl wrote:
> @marcus-h
> Happy new year and please review :-)
>
Thanks and same to you!:)

> diff --git a/osc/core.py b/osc/core.py
> index 965ec24b..cc8ce463 100644
> --- a/osc/core.py
> +++ b/osc/core.py
> @@ -4186,12 +4186,15 @@ def create_release_request(apiurl, src_project, message=''):
>      return r
>
>  # create a maintenance incident per request
> -def create_maintenance_request(apiurl, src_project, src_packages, tgt_project, tgt_releaseproject, opt_sourceupdate, message='', enforce_branching=False):
> +def create_maintenance_request(apiurl, src_project, src_packages, tgt_project, tgt_releaseproject, opt_sourceupdate, message='', enforce_branching=False, rev=None):
>      import cgi
>      r = Request()
>      if src_packages:
>          for p in src_packages:
> -            r.add_action('maintenance_incident', src_project=src_project, src_package=p, tgt_project=tgt_project, tgt_releaseproject=tgt_releaseproject, opt_sourceupdate = opt_sourceupdate)
> +            if rev:
> +                r.add_action('maintenance_incident', src_project=src_project, src_package=p, src_rev=rev, tgt_project=tgt_project, tgt_releaseproject=tgt_releaseproject, opt_sourceupdate = opt_sourceupdate)
> +            else:
> +                r.add_action('maintenance_incident', src_project=src_project, src_package=p, tgt_project=tgt_project, tgt_releaseproject=tgt_releaseproject, opt_sourceupdate = opt_sourceupdate)

We can always pass the src_rev argument (the Action class handles the None
value gracefully).

**Comment by lethliel** [comment]
Hi,

On 1/8/20 5:36 PM, Marcus Hüwe wrote:
> On 2020-01-08 06:40:55 -0800, Marco Strigl wrote:
>> @marcus-h
>> Happy new year and please review :-)
>>
> Thanks and same to you!:)
> 
>> diff --git a/osc/core.py b/osc/core.py
>> index 965ec24b..cc8ce463 100644
>> --- a/osc/core.py
>> +++ b/osc/core.py
>> @@ -4186,12 +4186,15 @@ def create_release_request(apiurl,
> src_project, message=''):
>> return r
>>
>> # create a maintenance incident per request
>> -def create_maintenance_request(apiurl, src_project, src_packages,
> tgt_project, tgt_releaseproject, opt_sourceupdate, message='',
> enforce_branching=False):
>> +def create_maintenance_request(apiurl, src_project, src_packages,
> tgt_project, tgt_releaseproject, opt_sourceupdate, message='',
> enforce_branching=False, rev=None):
>> import cgi
>> r = Request()
>> if src_packages:
>> for p in src_packages:
>> - r.add_action('maintenance_incident', src_project=src_project,
> src_package=p, tgt_project=tgt_project,
> tgt_releaseproject=tgt_releaseproject, opt_sourceupdate = opt_sourceupdate)
>> + if rev:
>> + r.add_action('maintenance_incident', src_project=src_project,
> src_package=p, src_rev=rev, tgt_project=tgt_project,
> tgt_releaseproject=tgt_releaseproject, opt_sourceupdate = opt_sourceupdate)
>> + else:
>> + r.add_action('maintenance_incident', src_project=src_project,
> src_package=p, tgt_project=tgt_project,
> tgt_releaseproject=tgt_releaseproject, opt_sourceupdate = opt_sourceupdate)
> 
> We can always pass the src_rev argument (the Action class handles the None
> value gracefully).
> 

You are right. I know always pass the src_rev argument

**Comment by marcus-h** [comment]
Merged. Thanks!

**Pull request merged**
