### PR TITLE
remove UrlGrabber to enable python3 

### PR DESCRIPTION
**Pull request by lethliel**
This pull request removes urlgrabber from osc. 
The mirror and grabber functions were moved to grabber.py

The progressbar function from Urlgrabber was replaced by the module progressbar.

@marcus-h: we discussed the changes already. 

This is the first of many PR to enable python3 in osc.

### CODE REVIEW

**Comment by lethliel** [comment]
replace urlgrabber to enable python3 compatibility

- new module grabber.py
  * Error Class MGError for grabber related errors
  * OscMirrorGroup to keep urlgrabber.mirrorgroup behavior
  * OscFileGrabber moved here

- meter.py
  * reworked to use progressbar module instead of progressbar
    of urlgrabber and simplified the module.

- babysitter.py
  * changed URLGrabError to own MGError

- build.py
  * removed adding of url_local to urllist. (not needed anymore)
  * removed URLGrabError

- commandline.py
  * switched from urlgrabber.urlgrab to OscFileGrabber().urlgrab

- core.py
  * reworked progressbar behavior

- fetch.py
  * removed join_url (not needed anymore)
  * moved OscFileGrabber to grabber.py
  * removed failureReport (not needed anymore)
  * switched error handling from URLGrabError to either HTTPError or
    MGError

- rpmquery.py
  * fixed tabs (indenting errors with python3)

- changed documentation

**Comment by marcus-h** [comment]
First of all thanks for the patch! LGTM in general. However,
some comments below:

On 2018-05-03 01:27:01 -0700, Marco Strigl wrote:
> diff --git a/osc/__init__.py b/osc/__init__.py
> index 7872a4e5..475cc39e 100644
> --- a/osc/__init__.py
> +++ b/osc/__init__.py
> @@ -1,3 +1,3 @@
> -__all__ = ['babysitter', 'core', 'commandline', 'oscerr', 'othermethods', 'build', 'fetch', 'meter']
> +__all__ = ['babysitter', 'core', 'commandline', 'oscerr', 'build', 'fetch', 'meter', 'grabber']

Actually unrelated.

> diff --git a/osc/babysitter.py b/osc/babysitter.py
> index 284a3d1..5e1aa54 100644
> --- a/osc/babysitter.py
> +++ b/osc/babysitter.py
> @@ -132,8 +132,8 @@ def run(prg, argv=None):
>          print(e, file=sys.stderr)
>      except URLError as e:
>          print('Failed to reach a server:\n', e.reason, file=sys.stderr)
> -    except URLGrabError as e:
> -        print('Failed to grab %s: %s' % (e.url, e.strerror), file=sys.stderr)
> +    except MGError as e:
> +        print('Failed to grab %s: %s' % (e.errno, e.strerror), file=sys.stderr)

Hmm storing the url in errno? After looking at the code, errno is
indeed no url. Hence, the error message is probably not too helpful...

> diff --git a/osc/commandline.py b/osc/commandline.py
> index 87f8a4f..5d94c88 100644
> --- a/osc/commandline.py
> +++ b/osc/commandline.py
> @@ -7749,8 +7749,8 @@ Please submit there instead, or use --nodevelproject to force direct submission.
>  
>          if '://' in srpm:
>              print('trying to fetch', srpm)
> -            import urlgrabber
> -            urlgrabber.urlgrab(srpm)
> +            from .grabber import OscFileGrabber
> +            OscFileGrabber().urlgrab(srpm)

A filename parameter is missing.

> diff --git a/osc/fetch.py b/osc/fetch.py
> index b96d1ae..3ded232 100644
> --- a/osc/fetch.py
> +++ b/osc/fetch.py
> @@ -290,7 +244,6 @@ class Fetcher:
>                      self.fetch(i)
>                      if self.progress_obj:
>                          print("  %d/%d\r" % (done, needed), end=' ')
> -                        sys.stdout.flush()
>  
Why did you remove the flush? This will probably "break" the output
in most cases (unless, for instance, you run sth. like
"stdbuf -o 0 osc...").


> @@ -311,7 +264,17 @@ class Fetcher:
>              try:
>                  if self.offline and not os.path.exists(dest):
>                      # may need to try parent
> -                    raise URLGrabError(2)
> +                    if self.http_debug:
> +                        print("can't fetch key for %s: %s" % (i, e.strerror), file=sys.stderr)
> +                        print("url: %s" % url, file=sys.stderr)
> +
> +                    if os.path.exists(dest):
> +                        os.unlink(dest)
> +
Hmm this is dead code (dest will never exist (in this particular case)).

> +                    l = i.rsplit(':', 1)
> +                    # try key from parent project
> +                    if len(l) > 1 and l[1] and not l[0] in buildinfo.projects:
> +                        prjs.append(l[0])
>                  elif not self.offline:
>                      OscFileGrabber().urlgrab(url, dest)
>                  # not that many keys usually
> @@ -324,24 +287,12 @@ class Fetcher:
>                  if os.path.exists(dest):
>                      os.unlink(dest)
>                  sys.exit(0)
> -            except URLGrabError as e:
> +            except HTTPError as e:
>                  # Not found is okay, let's go to the next project
> -                if e.errno == 14 and e.code != 404:
> +                if e.code != 404:
>                      print("Invalid answer from server", e, file=sys.stderr)
>                      sys.exit(1)
>  
> -                if self.http_debug:
> -                    print("can't fetch key for %s: %s" % (i, e.strerror), file=sys.stderr)
> -                    print("url: %s" % url, file=sys.stderr)
> -
> -                if os.path.exists(dest):
> -                    os.unlink(dest)
> -
> -                l = i.rsplit(':', 1)
> -                # try key from parent project
> -                if len(l) > 1 and l[1] and not l[0] in buildinfo.projects:
> -                    prjs.append(l[0])
> -

Removing this code is wrong. We still need to try the parent project(s).
For instance, openSUSE:Tools:Unstable has no key, but openSUSE:Tools has
one.

> diff --git a/osc/grabber.py b/osc/grabber.py
> new file mode 100644
> index 0000000..0878dd6
> --- /dev/null
> +++ b/osc/grabber.py
> +import sys
> +import os.path
> +from shutil import copyfile

copyfile is never used.

> +from .core import streamfile
> +
> +try:
> +    from urllib.parse import unquote
> +    from urllib.request import HTTPError
> +except ImportError:
> +    from urllib2 import HTTPError
> +    from urllib import unquote
> +
unquote is never used.

> +
> +class MGError(IOError):
> +    pass
> +
Hmm do we really need to inherit from IOError (see also the
comment for the babysitter.py)? (But I'm fine with it...)

> +class OscMirrorGroup(object):
> +    def __init__(self, grabber, mirrors):
> +        self._grabber = grabber
> +        self._mirrors = mirrors
> +
> +    def urlgrab(self, url, filename=None, text=None):
> +        tries = 0
> +        for mirror in self._mirrors:
> +            try:
> +                self._grabber.urlgrab(mirror, filename, text)
> +            except HTTPError as e:
> +                print('Error %s' % e.code)
> +                if e.code == 414:
> +                    raise HTTPError(e)

The raise will result in a TypeError... HTTPError takes more than
one argument. Why do we care about 414 at all?

> +                tries += 1
> +
> +        if len(self._mirrors) == tries:
> +            raise MGError(256, 'No mirrors left')

Hmm maybe we should provide a constant for this... but ok.

> diff --git a/osc/util/rpmquery.py b/osc/util/rpmquery.py
> index cba67d8..0bf2835 100644
> --- a/osc/util/rpmquery.py
> +++ b/osc/util/rpmquery.py
> @@ -166,7 +166,7 @@ class RpmQuery(packagequery.PackageQuery, packagequery.PackageQueryResult):
>      def __reqprov(self, tag, flags, version, strong=None):
>          pnames = self.header.gettag(tag)
>          if not pnames:
> -	    return []
> +            return []

Actually unrelated.

**Comment by lethliel** [comment]
On 05/13/2018 08:05 PM, Marcus Hüwe  wrote:
>> - except URLGrabError as e:
>> - print('Failed to grab %s: %s' % (e.url, e.strerror), file=sys.stderr)
>> + except MGError as e:
>> + print('Failed to grab %s: %s' % (e.errno, e.strerror), file=sys.stderr)
> 
> Hmm storing the url in errno? After looking at the code, errno is
> indeed no url. Hence, the error message is probably not too helpful...
> 

I changed it. The url is now part of e.strerror. Now the message makes sense again

>> - import urlgrabber
>> - urlgrabber.urlgrab(srpm)
>> + from .grabber import OscFileGrabber
>> + OscFileGrabber().urlgrab(srpm)
> 
> A filename parameter is missing.
>

added filename=None and no filename given handling to urlgrab function. [1]

 
>> diff --git a/osc/fetch.py b/osc/fetch.py
>> index b96d1ae..3ded232 100644
>> --- a/osc/fetch.py
>> +++ b/osc/fetch.py
>> @@ -290,7 +244,6 @@ class Fetcher:
>> self.fetch(i)
>> if self.progress_obj:
>> print(" %d/%d\r" % (done, needed), end=' ')
>> - sys.stdout.flush()
>>
> Why did you remove the flush? This will probably "break" the output
> in most cases (unless, for instance, you run sth. like
> "stdbuf -o 0 osc...").
> 

With the flush the progressbar is printed twice what looks kind of weird. 
This does not break any output. 

> 
>> @@ -311,7 +264,17 @@ class Fetcher:
>>
>> - if self.http_debug:
>> - print("can't fetch key for %s: %s" % (i, e.strerror), file=sys.stderr)
>> - print("url: %s" % url, file=sys.stderr)
>> -
>> - if os.path.exists(dest):
>> - os.unlink(dest)
>> -
>> - l = i.rsplit(':', 1)
>> - # try key from parent project
>> - if len(l) > 1 and l[1] and not l[0] in buildinfo.projects:
>> - prjs.append(l[0])
>> -
> 
> Removing this code is wrong. We still need to try the parent project(s).
> For instance, openSUSE:Tools:Unstable has no key, but openSUSE:Tools has
> one.

moved the code back to the exception handling. In the offline case a 'hand crafted'
404 is now raised. (I don't know if this can be done better, but so I need only one
exception path)

> 
>> diff --git a/osc/grabber.py b/osc/grabber.py
>> +from shutil import copyfile
> 
> copyfile is never used.
>

removed
 
>> +from .core import streamfile
>> +
>> +try:
>> + from urllib.parse import unquote
>> + from urllib.request import HTTPError
>> +except ImportError:
>> + from urllib2 import HTTPError
>> + from urllib import unquote
>> +
> unquote is never used.
> 

now it is used for [1]

>> + if e.code == 414:
>> + raise HTTPError(e)
> 
> The raise will result in a TypeError... HTTPError takes more than
> one argument. Why do we care about 414 at all?
>

removed the 414 Error. 

>> diff --git a/osc/util/rpmquery.py b/osc/util/rpmquery.py
>> index cba67d8..0bf2835 100644
>> --- a/osc/util/rpmquery.py
>> +++ b/osc/util/rpmquery.py
>> @@ -166,7 +166,7 @@ class RpmQuery(packagequery.PackageQuery, packagequery.PackageQueryResult):
>> def __reqprov(self, tag, flags, version, strong=None):
>> pnames = self.header.gettag(tag)
>> if not pnames:
>> - return []
>> + return []
> 
> Actually unrelated.
> 

changed back. opened new PR for this: https://github.com/openSUSE/osc/pull/431

**Comment by marcus-h** [comment]
Since my mail reply did not get through (for whatever reason...), here's the orginal message:

----- Forwarded message from Marcus Hüwe <suse-tux@gmx.de> -----

Date: Tue, 14 Aug 2018 00:08:52 +0200

**Comment by marcus-h** [comment]
Hmmpf simply pasting this message was probably not the smartest idea...
Maybe "I'm too old for this sh*t"...

**Comment by lethliel** [comment]
I will try to decode your comment tomorrow :-)

I would then just drop the counter, because in the most cases it is seen only for not more than a second.

**Comment by lethliel** [comment]
Ok. Took me some time because of vacation and sickness, but:

* fixed the counting. [xx/yy] is now set as a prefix if progressbar is used. This looks like: 
`[1/140] (openSUSE:Factory) liblua5_3-5-5.3.4-1.9.x86_64.rpm: 100%|#######################| Time: 0:00:00`

* The srpm is now checked for a tailing '/' in do_importsrcpkg. I think this is all we need for now. 

* removed the MGError from babysitter.py as it is never reached. 

* removed flow control through exception handling in fetch.py (parent prj determination) and introduced try_parent variable

* added return statement to urlgrab function in OscMirrorGroup class. 

* switched to True/False return statements in OscMirrorGroup

@marcus-h please review

**Comment by marcus-h** [comment]
Thanks for the updates! I think we are almost done!:)

On 2018-10-09 01:09:41 -0700, Marco Strigl wrote:
> * fixed the counting. [xx/yy] is now set as a prefix if progressbar is used. This looks like: 
> `[1/140] (openSUSE:Factory) liblua5_3-5-5.3.4-1.9.x86_64.rpm: 100%|#######################| Time: 0:00:00`
> 
Cool!

> * The srpm is now checked for a tailing '/' in do_importsrcpkg. I think this is all we need for now. 
> 
Hmm I'm still not too fond of manually constructing the filename in
OscFileGrabber.urlgrab... but I think it's ok for now.

> * removed the MGError from babysitter.py as it is never reached. 
> 
Ok. Can you also remove the other MGError references that are
floating around? (Just the class definition and an import)

> * removed flow control through exception handling in fetch.py (parent prj determination) and introduced try_parent variable
> 
Great! This greatly simplifies the code:)

> * added return statement to urlgrab function in OscMirrorGroup class. 
> 
> * switched to True/False return statements in OscMirrorGroup
> 
Ok.


> diff --git a/osc/fetch.py b/osc/fetch.py
> index b96d1ae..6c38330 100644
> --- a/osc/fetch.py
> +++ b/osc/fetch.py
> @@ -181,33 +134,33 @@ class Fetcher:

...
  
> -        try:
> -            with tempfile.NamedTemporaryFile(prefix='osc_build',
> -                                             delete=False) as tmpfile:
> -                mg.urlgrab(pac.filename, filename=tmpfile.name,
> -                           text='%s(%s) %s' % (prefix, pac.project, pac.filename))
> +        with tempfile.NamedTemporaryFile(prefix='osc_build',
> +                                         delete=False) as tmpfile:
> +            mg_stat = mg.urlgrab(pac.filename, filename=tmpfile.name,
> +                       text='%s(%s) %s' % (prefix, pac.project, pac.filename))
> +            if mg_stat:
>                  self.move_package(tmpfile.name, pac.localdir, pac)
> -        except URLGrabError as e:
> -            if self.enable_cpio and e.errno == 256:
> +        if os.path.exists(tmpfile.name):
> +            os.unlink(tmpfile.name)
> +        if mg_stat == False:

"if not mg_stat:" :)

> +            if self.enable_cpio:
> +                print('%s/%s: attempting download from api, since not found'
> +                      % (pac.project, pac.name))
>                  self.__add_cpio(pac)
>                  return
>              print()
> -            print('Error:', e.strerror, file=sys.stderr)
> +            print('Error:', file=sys.stderr)

Idea: move the 'Error:' to the subsequent print? (print('Error: Failed...'))

>              print('Failed to retrieve %s from the following locations '
>                    '(in order):' % pac.filename, file=sys.stderr)
>              print('\n'.join(pac.urllist), file=sys.stderr)
>              sys.exit(1)
> -        finally:
> -            if os.path.exists(tmpfile.name):
> -                os.unlink(tmpfile.name)
>  
We should keep the try-finally construct, otherwise we might "pollute"
the tmpdir. For instance, assume the code executes mg.urlgrab and the
user presses CTRL-c => the tmpfile is not removed.


> @@ -285,12 +238,12 @@ class Fetcher:
>                      continue
>                  try:
>                      # if there isn't a progress bar, there is no output at all
> +                    prefix = ''
>                      if not self.progress_obj:
>                          print('%d/%d (%s) %s' % (done, needed, i.project, i.filename))
> -                    self.fetch(i)
>                      if self.progress_obj:

Very minor: now this looks a bit strange - maybe just replace
the "if self.progress_obj:" with an "else:" :)

> -                        print("  %d/%d\r" % (done, needed), end=' ')
> -                        sys.stdout.flush()
> +                        prefix = '[%d/%d] ' % (done, needed)
> +                    self.fetch(i, prefix=prefix)
>  
>                  except KeyboardInterrupt:
>                      print('Cancelled by user (ctrl-c)')
> @@ -308,10 +261,11 @@ class Fetcher:
>              dest += '/_pubkey'
>  
>              url = makeurl(buildinfo.apiurl, ['source', i, '_pubkey'])
> +            try_parent = False
>              try:
>                  if self.offline and not os.path.exists(dest):
>                      # may need to try parent
> -                    raise URLGrabError(2)
> +                    try_parent = True
>                  elif not self.offline:
>                      OscFileGrabber().urlgrab(url, dest)
>                  # not that many keys usually
> @@ -324,15 +278,16 @@ class Fetcher:
>                  if os.path.exists(dest):
>                      os.unlink(dest)
>                  sys.exit(0)
> -            except URLGrabError as e:
> +            except HTTPError as e:
>                  # Not found is okay, let's go to the next project
> -                if e.errno == 14 and e.code != 404:
> +                if e.code != 404:
>                      print("Invalid answer from server", e, file=sys.stderr)
>                      sys.exit(1)
>  
We have to set "try_parent" to True here (otherwise we don't do a parent
lookup).

> +            if try_parent == True:

"if try_parent:" :)

>                  if self.http_debug:
> -                    print("can't fetch key for %s: %s" % (i, e.strerror), file=sys.stderr)
> -                    print("url: %s" % url, file=sys.stderr)
> +                        print("can't fetch key for %s: %s" % (i, e.strerror), file=sys.stderr)
> +                        print("url: %s" % url, file=sys.stderr)
>  
Minor: too much indention.

>                  if os.path.exists(dest):
>                      os.unlink(dest)
> diff --git a/osc/grabber.py b/osc/grabber.py
> new file mode 100644
> index 0000000..636d19f
> --- /dev/null
> +++ b/osc/grabber.py
> +class OscMirrorGroup(object):

...

> +    def urlgrab(self, url, filename=None, text=None):
> +        tries = 0
> +        for mirror in self._mirrors:
> +            try:
> +                self._grabber.urlgrab(mirror, filename, text)
> +                return True
> +            except HTTPError as e:
> +                print('Error %s' % e.code)
> +                tries += 1
> +
> +        if len(self._mirrors) == tries:
> +            return False

If this codepath is reached, we always have len(self._mirrors) == tries.
Hence, we can simply do a "return False" at the end of the method.

**Comment by lethliel** [comment]
@marcus-h: 

Made the suggested changes and removed all MGErrors :-)

**Comment by marcus-h** [comment]
On 2018-10-19 07:43:17 +0000, Marco Strigl wrote:
> @marcus-h: 
> 
> Made the suggested changes and removed all MGErrors :-) 
> 
Apart from a very minor remark it looks really good (I just removed
a "superfluous" print(...) in commit ad1450a1f71b2c4bce07009bce5937869aac9e4c).

Thanks a lot for your effort and your patience! Merged:)

**Comment by marcus-h** [comment]
On 2018-11-01 20:00:33 +0100, Marcus Hüwe wrote:
> On 2018-10-19 07:43:17 +0000, Marco Strigl wrote:
> > @marcus-h: 
> > 
> > Made the suggested changes and removed all MGErrors :-) 
> > 
> Apart from a very minor remark it looks really good (I just removed
> a "superfluous" print(...) in commit ad1450a1f71b2c4bce07009bce5937869aac9e4c).
> 
> Thanks a lot for your effort and your patience! Merged:)

Btw., another minor remark: the current implementation of the progress
bar is quite "noisy" if the line length exceeds the size of the
terminal window, but that's something we could fix later...

Anyway, thanks for the PR!

**Pull request merged**
