### PR TITLE
dealing with new exception errors

### PR DESCRIPTION
**Pull request by adrianschroeter**
Consider this more a bugreport then a pull request, but osc is bascially unusable here due to exceptions.

### CODE REVIEW

**Comment by lethliel** [comment]
@adrianschroeter Do you have an example of other exceptions that can occur?

**Comment by lethliel** [comment]
And it what way does this make it unusable for you?

**Comment by adrianschroeter** [comment]
On Montag, 24. Februar 2020, 13:49:26 CET Marco Strigl wrote:
> @adrianschroeter Do you have an example of other exceptions that can occur? 

Just grepe through the python modules for "raise" statements....

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by marcus-h** [comment]
On 2020-02-24 22:57:17 -0800, Adrian Schröter wrote:
> On Montag, 24. Februar 2020, 13:49:26 CET Marco Strigl wrote:
> > @adrianschroeter Do you have an example of other exceptions that can occur?
>
> Just grepe through the python modules for "raise" statements....
>
Hmm hmm if you see an exception here, then some keyring backend is most
likely buggy/misbehaving:

> diff --git a/osc/credentials.py b/osc/credentials.py
> index d2ce493b..524a47b1 100644
> --- a/osc/credentials.py
> +++ b/osc/credentials.py
> @@ -8,7 +8,9 @@
>      from urlparse import urlsplit
>  try:
>      import keyring
> -except ImportError:
> +except:
> +    # typical ones are ImportError or secretstorage.exceptions.ItemNotFoundException
> +    # but seems not to be limited to them, so catch global

I just had a _very quick_ glance at the SecretService module and the
secretstorage code but I can't see why it should raise such an exception
during the import.

marcus@linux:~> rpm -q python3-SecretStorage python3-keyring
python3-SecretStorage-2.3.1-7.1.noarch
python3-keyring-18.0.1-1.4.noarch
marcus@linux:~>

Can you please post a traceback + the output of the "rpm -q ..." command?:)

**Comment by dmach** [comment]
@adrianschroeter could you change it that it silently passes on ImportError (keyring not installed)
and prints a warning to stderr (something like "Warning: unable to use keyring due to an internal error: ", e)  on catching `BaseException`?

**Comment by dmach** [comment]
@adrianschroeter could you change it that it silently passes on ImportError (keyring not installed)
and prints a warning to stderr (something like "Warning: unable to use keyring due to an internal error: ", e)  on catching `BaseException`?

**Comment by lethliel** [comment]
LGTM

**Pull request merged**
