### PR TITLE
Pretty print `osc dists` output

### PR DESCRIPTION
**Pull request by abitrolly**
This table formatting code calculates the widest column before printing. It can be generalized for other tabular data if needed.

### Before

```python
distribution              project                   repository                reponame
------------              -------                   ----------                --------
openSUSE Tumbleweed       openSUSE:Factory          snapshot                  openSUSE_Tumbleweed
openSUSE Leap 15.2        openSUSE:Leap:15.2        standard                  openSUSE_Leap_15.2
openSUSE Leap 15.2 ARM    openSUSE:Leap:15.2:ARM    ports                     openSUSE_Leap_15.2_ARM
openSUSE Leap 15.2 PowerPC openSUSE:Leap:15.2:PowerPC ports                     openSUSE_Leap_15.2_PowerPC
openSUSE Leap 15.1        openSUSE:Leap:15.1        standard                  openSUSE_Leap_15.1
openSUSE Leap 15.1 ARM    openSUSE:Leap:15.1:ARM    ports                     openSUSE_Leap_15.1_ARM
openSUSE Leap 15.1 PowerPC openSUSE:Leap:15.1:PowerPC ports                     openSUSE_Leap_15.1_PowerPC
openSUSE Factory RISCV    openSUSE:Factory:RISCV    standard                  openSUSE_Factory_RISCV
openSUSE Factory ARM      openSUSE:Factory:ARM      standard                  openSUSE_Factory_ARM
openSUSE Factory PowerPC  openSUSE:Factory:PowerPC  standard                  openSUSE_Factory_PowerPC
openSUSE Factory zSystems openSUSE:Factory:zSystems standard                  openSUSE_Factory_zSystems
openSUSE Backports for SLE 15 SP2 openSUSE:Backports:SLE-15-SP2 standard                  SLE_15_SP2_Backports
openSUSE Backports for SLE 15 SP1 openSUSE:Backports:SLE-15-SP1 standard                  SLE_15_SP1_Backports
openSUSE Backports for SLE 15 openSUSE:Backports:SLE-15 standard                  SLE_15_Backports
openSUSE Backports for SLE 12 SP5 openSUSE:Backports:SLE-12-SP5 standard                  SLE_12_SP5_Backports
openSUSE Backports for SLE 12 SP4 openSUSE:Backports:SLE-12-SP4 standard                  SLE_12_SP4_Backports
openSUSE Backports for SLE 12 SP3 openSUSE:Backports:SLE-12-SP3 standard                  SLE_12_SP3_Backports
openSUSE Backports for SLE 12 SP2 openSUSE:Backports:SLE-12-SP2 standard                  SLE_12_SP2_Backports
openSUSE Backports for SLE 12 SP1 openSUSE:Backports:SLE-12-SP1 standard                  SLE_12_SP1_Backports
openSUSE Backports for SLE 12 SP0 openSUSE:Backports:SLE-12 standard                  SLE_12_Backports
SUSE SLE-15-SP2           SUSE:SLE-15-SP2:GA        standard                  SLE_15_SP2
SUSE SLE-15-SP1           SUSE:SLE-15-SP1:GA        standard                  SLE_15_SP1
SUSE SLE-15               SUSE:SLE-15:GA            standard                  SLE_15
SUSE SLE-12-SP5           SUSE:SLE-12-SP5:GA        standard                  SLE_12_SP5
SUSE SLE-12-SP4           SUSE:SLE-12-SP4:GA        standard                  SLE_12_SP4
SUSE SLE-12-SP3           SUSE:SLE-12-SP3:GA        standard                  SLE_12_SP3
SUSE SLE-12-SP2           SUSE:SLE-12-SP2:GA        standard                  SLE_12_SP2
SUSE SLE-12-SP1           SUSE:SLE-12-SP1:GA        standard                  SLE_12_SP1
SUSE SLE-12               SUSE:SLE-12:GA            standard                  SLE_12
...
```

### After

```python
distribution                       project                        repository  reponame
---------------------------------  -----------------------------  ----------  ----------
openSUSE Tumbleweed                openSUSE:Factory               snapshot    openSUSE_Tumbleweed
openSUSE Leap 15.2                 openSUSE:Leap:15.2             standard    openSUSE_Leap_15.2
openSUSE Leap 15.2 ARM             openSUSE:Leap:15.2:ARM         ports       openSUSE_Leap_15.2_ARM
openSUSE Leap 15.2 PowerPC         openSUSE:Leap:15.2:PowerPC     ports       openSUSE_Leap_15.2_PowerPC
openSUSE Leap 15.1                 openSUSE:Leap:15.1             standard    openSUSE_Leap_15.1
openSUSE Leap 15.1 ARM             openSUSE:Leap:15.1:ARM         ports       openSUSE_Leap_15.1_ARM
openSUSE Leap 15.1 PowerPC         openSUSE:Leap:15.1:PowerPC     ports       openSUSE_Leap_15.1_PowerPC
openSUSE Factory RISCV             openSUSE:Factory:RISCV         standard    openSUSE_Factory_RISCV
openSUSE Factory ARM               openSUSE:Factory:ARM           standard    openSUSE_Factory_ARM
openSUSE Factory PowerPC           openSUSE:Factory:PowerPC       standard    openSUSE_Factory_PowerPC
openSUSE Factory zSystems          openSUSE:Factory:zSystems      standard    openSUSE_Factory_zSystems
openSUSE Backports for SLE 15 SP2  openSUSE:Backports:SLE-15-SP2  standard    SLE_15_SP2_Backports
openSUSE Backports for SLE 15 SP1  openSUSE:Backports:SLE-15-SP1  standard    SLE_15_SP1_Backports
openSUSE Backports for SLE 15      openSUSE:Backports:SLE-15      standard    SLE_15_Backports
openSUSE Backports for SLE 12 SP5  openSUSE:Backports:SLE-12-SP5  standard    SLE_12_SP5_Backports
openSUSE Backports for SLE 12 SP4  openSUSE:Backports:SLE-12-SP4  standard    SLE_12_SP4_Backports
openSUSE Backports for SLE 12 SP3  openSUSE:Backports:SLE-12-SP3  standard    SLE_12_SP3_Backports
openSUSE Backports for SLE 12 SP2  openSUSE:Backports:SLE-12-SP2  standard    SLE_12_SP2_Backports
openSUSE Backports for SLE 12 SP1  openSUSE:Backports:SLE-12-SP1  standard    SLE_12_SP1_Backports
openSUSE Backports for SLE 12 SP0  openSUSE:Backports:SLE-12      standard    SLE_12_Backports
SUSE SLE-15-SP2                    SUSE:SLE-15-SP2:GA             standard    SLE_15_SP2
SUSE SLE-15-SP1                    SUSE:SLE-15-SP1:GA             standard    SLE_15_SP1
SUSE SLE-15                        SUSE:SLE-15:GA                 standard    SLE_15
SUSE SLE-12-SP5                    SUSE:SLE-12-SP5:GA             standard    SLE_12_SP5
SUSE SLE-12-SP4                    SUSE:SLE-12-SP4:GA             standard    SLE_12_SP4
SUSE SLE-12-SP3                    SUSE:SLE-12-SP3:GA             standard    SLE_12_SP3
SUSE SLE-12-SP2                    SUSE:SLE-12-SP2:GA             standard    SLE_12_SP2
SUSE SLE-12-SP1                    SUSE:SLE-12-SP1:GA             standard    SLE_12_SP1
SUSE SLE-12                        SUSE:SLE-12:GA                 standard    SLE_12
...
```

### CODE REVIEW

**Comment by marcus-h** [comment]
On 2020-11-14 08:58:26 -0800, Anatoli Babenia wrote:
> This table formatting code calculates the widest column before printing. It can be generalized for other tabular data if needed.
>
What about the following patch, which simply uses core.build_table?

```
diff --git a/osc/core.py b/osc/core.py
index 067888f..9af7263 100644
--- a/osc/core.py
+++ b/osc/core.py
@@ -5604,19 +5604,14 @@ def get_distibutions(apiurl, discon=False):

         for node in root.findall('distribution'):
             rmap = {}
-            for node2 in node.findall('name'):
-                rmap['name'] = node2.text
-            for node3 in node.findall('project'):
-                rmap['project'] = node3.text
-            for node4 in node.findall('repository'):
-                rmap['repository'] = node4.text
-            for node5 in node.findall('reponame'):
-                rmap['reponame'] = node5.text
-            r.append(result_line_templ % rmap)
-
-        r.insert(0, 'distribution              project                   repository                reponame')
-        r.insert(1, '------------              -------                   ----------                --------')
-
+            for tag in ('name', 'project', 'repository', 'reponame'):
+                elm = node.find(tag)
+                if elm is None:
+                    raise ValueError('no such child: %s' % tag)
+                r.append(elm.text)
+
+        headline = ('distribution', 'project', 'repository', 'reponame')
+        r = build_table(4, r, headline, 2)
     return r


```

**Comment by abitrolly** [comment]
@marcus-h from [the code](https://github.com/openSUSE/osc/blob/d7594ddeda636509690ceed3b2b3a55634e578c1/osc/core.py#L6700) it looks like `build_table` doesn't separate headers from the content.

It also confusing that structured data needs to be flattened to become structured again with explicitly passed dimensions. To me, the API to this function could take only two arguments - list of OrderedDict entries and headers.

**Comment by dmach** [comment]
I'd also consider using `smartcols` library to format the output.
It's an additional dependency, but it's not that big deal after taking a closer look.
The C version is part of util-linux (see `ls`, `lsblk` for example) and there's a python wrapper: https://github.com/ignatenkobrain/python-smartcols.
I have quite good experience with it from the DNF package manager, although we switched to using the C API completely because the underlying libdnf is in C++.

Some references:
- http://karelzak.blogspot.com/2016/
- http://ftp.ntu.edu.tw/pub/linux/utils/util-linux/v2.37/libsmartcols-docs/

This is how the output using `build_table` looks like on a terminal 80 characters wide:
```
distribution                       project                        repository  re
poname
openEuler 20.03                    openEuler:20.03                standard    op
enEuler_20.03
openEuler 21.03                    openEuler:21.03                standard    op
enEuler_21.03
...
openSUSE Backports for SLE 15 SP4  openSUSE:Backports:SLE-15-SP4  standard    15
.4
openSUSE Backports for SLE 15 SP3  openSUSE:Backports:SLE-15-SP3  standard    15
.3
```

The `smarcols` output can be even configured to be "smart" and split records over several lines (while keeping them altogether when piping to tools such as `grep`).
```
NAME                       PROJECT                REPOSITORY REPONAME
openEuler 20.03            openEuler:20.03        standard   openEuler_20.03
openEuler 21.03            openEuler:21.03        standard   openEuler_21.03
...
openSUSE Backports for SLE 15 SP4
                           openSUSE:Backports:SLE-15-SP4
                                                  standard   15.4
openSUSE Backports for SLE 15 SP3
                           openSUSE:Backports:SLE-15-SP3
                                                  standard   15.3
```

Let me know if this looks appealing to you.
I could take care of packaging python-smartcols in openSUSE and porting osc code to it.

**Comment by abitrolly** [comment]
No, I like my code more. :D Because it doesn't add external dependencies.

**Comment by dmach** [comment]
> No, I like my code more. :D Because it doesn't add external dependencies.

Ok, adding external deps is a fair point.
If we should handle this with our own code, it should be a reusable function rather than writing similar code over and over again for each such table. Couldn't you use and extend `build_table` instead?

**Comment by lethliel** [comment]
We will merge this right now. And perhaps refactor some code in a future output standardization project.

**Pull request merged**
