### PR TITLE
fixed IncompleteRead(0) error on long builds.

### LINKED ISSUE #402: IncompleteRead with osc buildlogtail
`osc buildlogtail` throws a IncompleteRead exception on long (stalled) buildlogs.

To reproduce this just add `sleep 600` to a spec file.

```
[   36s] copying and adjusting osc-wrapper.py -> build/scripts-2.7
[   36s] changing mode of build/scripts-2.7/osc_hotshot.py from 644 to 755
[   36s] changing mode of build/scripts-2.7/osc-wrapper.py from 644 to 755
[   36s] generating build/osc.1.gz
[   36s] + sleep 3000
IncompleteRead(0 bytes read)
```

### PR DESCRIPTION
**Pull request by lethliel**
catch IncompleteRead() and retry until retry_counter is reached. Then re-raise IncompleteRead().

fixes #402 

@marcus-h: please review (tested with python2 and python3)

### CODE REVIEW

**Comment by marcus-h** [comment]
On 2018-04-16 13:06:20 +0000, Marco Strigl wrote:
> sstatus object is introduced, which holds the state
> of the stream. If an incompleteRead is thrown the stream
> is restarted as long as retry_count is not reached (3)
> 
Can you post the traceback that you are trying to fix?

> @@ -6000,7 +6010,16 @@ def streamfile(url, http_meth = http_GET, bufsize=8192, data=None, progress_obj=
>  
>      read = 0
>      while True:
> -        data = xread(bufsize)
> +        try:
> +            data = xread(bufsize)
> +        except IncompleteRead as e:
> +            if sstatus:
> +                sstatus.set_broken(True)
> +                sstatus.retry_count += 1
> +                data = e.partial
> +            else:
> +                print('Stream was interrupted. Please restart stream')
> +                break

No way! In the else branch, the exception has to be re-raised. Just
printing a message and continuing can lead to lots of (probably hard
to debug) errors (partially written files etc.).

Why do we need this StreamStatus object? Can't we simply catch the
IncompleteRead error where needed? (To be honest, the StreamStatus
looks a bit "strange")

**Comment by lethliel** [comment]
On 04/16/2018 10:43 PM, Marcus Hüwe  wrote:
> On 2018-04-16 13:06:20 +0000, Marco Strigl wrote:
>> sstatus object is introduced, which holds the state
>> of the stream. If an incompleteRead is thrown the stream
>> is restarted as long as retry_count is not reached (3)
>>
> Can you post the traceback that you are trying to fix?

No Traceback. Just the output: 

```
[   36s] copying and adjusting osc-wrapper.py -> build/scripts-2.7
[   36s] changing mode of build/scripts-2.7/osc_hotshot.py from 644 to 755
[   36s] changing mode of build/scripts-2.7/osc-wrapper.py from 644 to 755
[   36s] generating build/osc.1.gz
[   36s] + sleep 3000
IncompleteRead(0 bytes read)
```

> 
>> @@ -6000,7 +6010,16 @@ def streamfile(url, http_meth = http_GET, bufsize=8192, data=None, progress_obj=
>>
>> read = 0
>> while True:
>> - data = xread(bufsize)
>> + try:
>> + data = xread(bufsize)
>> + except IncompleteRead as e:
>> + if sstatus:
>> + sstatus.set_broken(True)
>> + sstatus.retry_count += 1
>> + data = e.partial
>> + else:
>> + print('Stream was interrupted. Please restart stream')
>> + break
> 
> No way! In the else branch, the exception has to be re-raised. Just
> printing a message and continuing can lead to lots of (probably hard
> to debug) errors (partially written files etc.).

Since this isn't really an exception I thought to inform the user that he has
to restart the command is better than showing confusing tracebacks. And it breaks. 
It does not continue.

> 
> Why do we need this StreamStatus object? Can't we simply catch the
> IncompleteRead error where needed? (To be honest, the StreamStatus
> looks a bit "strange")

I wanted to hold the status sstream.broken over twi functions. I also increment the counter
in one function and use it in another one.

But I will check if I can do all the above in the print_buildlog function.

**Comment by marcus-h** [comment]
On 2018-04-17 07:46:30 +0000, Marco Strigl wrote:
> On 04/16/2018 10:43 PM, Marcus Hüwe  wrote:
> > On 2018-04-16 13:06:20 +0000, Marco Strigl wrote:
> > Can you post the traceback that you are trying to fix?
> 
> No Traceback. Just the output: 
> 
> ```
> [   36s] copying and adjusting osc-wrapper.py -> build/scripts-2.7
> [   36s] changing mode of build/scripts-2.7/osc_hotshot.py from 644 to 755
> [   36s] changing mode of build/scripts-2.7/osc-wrapper.py from 644 to 755
> [   36s] generating build/osc.1.gz
> [   36s] + sleep 3000
> IncompleteRead(0 bytes read)
> ```
> 
Hrm yes, we catch HTTPException.

> >> @@ -6000,7 +6010,16 @@ def streamfile(url, http_meth = http_GET, bufsize=8192, data=None, progress_obj=
> >>
> >> read = 0
> >> while True:
> >> - data = xread(bufsize)
> >> + try:
> >> + data = xread(bufsize)
> >> + except IncompleteRead as e:
> >> + if sstatus:
> >> + sstatus.set_broken(True)
> >> + sstatus.retry_count += 1
> >> + data = e.partial
> >> + else:
> >> + print('Stream was interrupted. Please restart stream')
> >> + break
> > 
> > No way! In the else branch, the exception has to be re-raised. Just
> > printing a message and continuing can lead to lots of (probably hard
> > to debug) errors (partially written files etc.).
> 
> Since this isn't really an exception I thought to inform the user that he has
> to restart the command is better than showing confusing tracebacks. And it breaks. 
> It does not continue.
> 
In all cases, except print_buildlog, osc continues with the incomplete
data (there are several users of streamfile (for instance, also the
checkout/update codepath)).

> > Why do we need this StreamStatus object? Can't we simply catch the
> > IncompleteRead error where needed? (To be honest, the StreamStatus
> > looks a bit "strange")
> 
> I wanted to hold the status sstream.broken over twi functions.

Hmm why is this needed? streamfile just sets it to broken and print_buildlog
reads it.

> I also increment the counter
> in one function and use it in another one.
> 
> But I will check if I can do all the above in the print_buildlog function. 
> 
Ok.

**Comment by lethliel** [comment]
On 04/17/2018 10:44 AM, Marcus Hüwe  wrote:
> On 2018-04-17 07:46:30 +0000, Marco Strigl wrote:
>> On 04/16/2018 10:43 PM, Marcus Hüwe wrote:
>> > On 2018-04-16 13:06:20 +0000, Marco Strigl wrote:
>> > Can you post the traceback that you are trying to fix?
>>

<SNIP>

> In all cases, except print_buildlog, osc continues with the incomplete
> data (there are several users of streamfile (for instance, also the
> checkout/update codepath)).
> 

Right. I have to remember: "My function is not the only caller" :) 

>> > Why do we need this StreamStatus object? Can't we simply catch the
>> > IncompleteRead error where needed? (To be honest, the StreamStatus
>> > looks a bit "strange")
>>
>> I wanted to hold the status sstream.broken over twi functions.
> 
> Hmm why is this needed? streamfile just sets it to broken and print_buildlog
> reads it.

I did the exception handling at the wrong function. If I handle the exception in 
the print_buildlog function this is not needed

> 
>> I also increment the counter
>> in one function and use it in another one.
>>
>> But I will check if I can do all the above in the print_buildlog function.
>>
> Ok.
>

Updated the commit and the PR description.

**Comment by marcus-h** [comment]
Almost perfect! But "strip_time" is not considered in print_data
anymore (it is always False).

**Comment by lethliel** [comment]
On 04/23/2018 10:28 PM, Marcus Hüwe  wrote:
> Almost perfect! But "strip_time" is not considered in print_data
> anymore (it is always False).

Now it gets considered.

**Comment by marcus-h** [comment]
On 2018-04-24 01:56:48 -0700, Marco Strigl wrote:
> On 04/23/2018 10:28 PM, Marcus Hüwe  wrote:
> > Almost perfect! But "strip_time" is not considered in print_data
> > anymore (it is always False).
> 
> Now it gets considered.
> 
Merged. Thanks!

**Pull request merged**
