### PR TITLE
[python3] python3 support for commandline module

### PR DESCRIPTION
**Pull request by lethliel**
* use cmp_to_key from functools for python 2.7 and higer
* use self written cmp_to_key for python 2.6
* a lot of bytestring handling and decoding

needs https://github.com/openSUSE/osc/pull/464 to work.

Merge only together with https://github.com/openSUSE/osc/pull/492

### CODE REVIEW

**Comment by z3ntu** [comment]
Could you also push the changes from here to the python3 branch? (I'm hitting the `root_new = ET.fromstring(''.join(meta))` line not being changed in the python3 branch)

**Comment by z3ntu** [comment]
You missed one `b` prefix at https://github.com/openSUSE/osc/blob/467bff9ebf46c3e464606c27a2479237f5ad311e/osc/commandline.py#L8471

**Comment by z3ntu** [comment]
Here's a patch:
```diff
diff --git a/osc/commandline.py b/osc/commandline.py
index e371a44b..e337be29 100644
--- a/osc/commandline.py
+++ b/osc/commandline.py
@@ -8469,7 +8469,7 @@ Please submit there instead, or use --nodevelproject to force direct submission.
         u = makeurl(apiurl, ['source', prj, package], query=query)
         f = http_GET(u)
         meta = f.readlines()
-        root_new = ET.fromstring(''.join(meta))
+        root_new = ET.fromstring(b''.join(meta))
         dir_new = { 'apiurl': apiurl, 'project': prj, 'package': package }
         dir_new['srcmd5'] = root_new.get('srcmd5')
         dir_new['entries'] = [[n.get('name'), n.get('md5')] for n in root_new.findall('entry')]
@@ -8513,7 +8513,7 @@ Please submit there instead, or use --nodevelproject to force direct submission.
         os.mkdir(destdir)
 
         Package.init_package(apiurl, target_prj, target_package, destdir)
-        store_write_string(destdir, '_files', ''.join(meta) + '\n')
+        store_write_string(destdir, '_files', b''.join(meta) + b'\n')
         store_write_string(destdir, '_linkrepair', '')
         pac = Package(destdir)
 

```

**Comment by lethliel** [comment]
@z3ntu Thanks for the catch. Will modify this PR.

**Comment by lethliel** [comment]
merged as discussed with @marcus-h on IRC

**Pull request merged**
