### PR TITLE
fix downloading from mirrors

### PR DESCRIPTION
**Pull request by adrianschroeter**
Some of our repositories have specific download urls. osc is ignoring
this so far and just tries to use the generic downloadurl

This code prefers definitions for individual path elements if they exist.
We could IMHO remove the old code, since old OBS instances would still
work via the api download fallback.

Real life examples for repo specific configs are on openSUSE all
repositories outside of the /repositories/ directory. eg.

  <path project="openSUSE:Tumbleweed" repository="dod" url="http://download.opensuse.org/tumbleweed/repo/oss/"/>

### CODE REVIEW

**Comment by Firstyear** [comment]
Hey there, I tried this out but this branch gives an error:

```
[william@pyrite 10:49] ~/development/obs_home/home:firstyear:kanidm/kanidm # PYTHONPATH=/home/william/development/osc python3 /home/william/development/osc/osc-wrapper.py build
Building kanidm.spec for openSUSE_Tumbleweed/x86_64
Getting buildconfig from server and store to /home/886b45ce-98b2-4d79-9069-c9ff25bc0232/development/obs_home/home:firstyear:kanidm/kanidm/.osc/_buildconfig-openSUSE_Tumbleweed-x86_64
Getting buildinfo from server and store to /home/886b45ce-98b2-4d79-9069-c9ff25bc0232/development/obs_home/home:firstyear:kanidm/kanidm/.osc/_buildinfo-openSUSE_Tumbleweed-x86_64.xml
Updating cache of required packages
Traceback (most recent call last):
  File "/home/william/development/osc/osc-wrapper.py", line 45, in <module>
    r = babysitter.run(osccli)
  File "/home/886b45ce-98b2-4d79-9069-c9ff25bc0232/development/osc/osc/babysitter.py", line 69, in run
    return prg.main(argv)
  File "/home/886b45ce-98b2-4d79-9069-c9ff25bc0232/development/osc/osc/cmdln.py", line 347, in main
    return self.cmd(args)
  File "/home/886b45ce-98b2-4d79-9069-c9ff25bc0232/development/osc/osc/cmdln.py", line 370, in cmd
    retval = self.onecmd(argv)
  File "/home/886b45ce-98b2-4d79-9069-c9ff25bc0232/development/osc/osc/cmdln.py", line 504, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/home/886b45ce-98b2-4d79-9069-c9ff25bc0232/development/osc/osc/cmdln.py", line 1235, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/home/886b45ce-98b2-4d79-9069-c9ff25bc0232/development/osc/osc/commandline.py", line 6724, in do_build
    return osc.build.main(self.get_api_url(), opts, args)
  File "/home/886b45ce-98b2-4d79-9069-c9ff25bc0232/development/osc/osc/build.py", line 1078, in main
    fetcher.run(bi)
  File "/home/886b45ce-98b2-4d79-9069-c9ff25bc0232/development/osc/osc/fetch.py", line 204, in run
    i.makeurls(self.cachedir, self.urllist, buildinfo.urls)
  File "/home/886b45ce-98b2-4d79-9069-c9ff25bc0232/development/osc/osc/build.py", line 288, in makeurls
    repo_specific_url = urls['%s/%s' % (self.project, self.repository)]
KeyError: 'openSUSE:Tumbleweed/dod'
```

I've dumped the state of the urls dict at that time, and it only contains:

```
DEBUG -> {'home:firstyear:kanidm/openSUSE_Tumbleweed': 'https://download.opensuse.org/repositories/home:/firstyear:/kanidm/openSUSE_Tumbleweed//%(arch)s/%(filename)s'}
```

So I think there may still be something missing here.

**Comment by adrianschroeter** [comment]
ups ... @Firstyear  please test again

**Comment by Firstyear** [comment]
Nope, still not working:

```
Updating cache of required packages
100.0% cache miss. 0/195 dependencies cached.

openSUSE:Tumbleweed/liblua5_4-5: attempting download from api, since not found
openSUSE:Tumbleweed/aaa_base: attempting download from api, since not found
openSUSE:Tumbleweed/attr: attempting download from api, since not found
openSUSE:Tumbleweed/bash: attempting download from api, since not found
openSUSE:Tumbleweed/coreutils: attempting download from api, since not found
openSUSE:Tumbleweed/diffutils: attempting download from api, since not found
openSUSE:Tumbleweed/filesystem: attempting download from api, since not found
openSUSE:Tumbleweed/fillup: attempting download from api, since not found
openSUSE:Tumbleweed/glibc: attempting download from api, since not found
openSUSE:Tumbleweed/grep: attempting download from api, since not found
```

```
commit 87daca6a2f88e7b22cf919e33348486996b43a8b (HEAD -> fix_download, github-aschroeter/fix_download)
```

**Comment by adrianschroeter** [comment]
that is a server side issue (missing partition support, will take care)

**Comment by adrianschroeter** [comment]
https://github.com/openSUSE/open-build-service/pull/11649

**Comment by Vogtinator** [comment]
Just tried the branch here, works!

**Comment by Firstyear** [comment]
@adrianschroeter That's done the trick, I have just tested and it works!

**Comment by marcus-h** [comment]
Cool! Though, I'm not too fond of the Pac.makeurls change. IMHO, the
new API looks a bit "strange". The following patch tries to avoid that
(it is based on this PR).

What do you think? (See also the XXX comment)

diff --git a/osc/build.py b/osc/build.py
index 89ebed8a..97117d54 100644
--- a/osc/build.py
+++ b/osc/build.py
@@ -176,6 +176,7 @@ class Buildinfo:
             self.deps.append(p)
         for node in root.findall('path'):
             # old simple list for compatibility
+            # XXX: really old? This is currently used for kiwi builds
             self.pathes.append(node.get('project')+"/"+node.get('repository'))
             # a hash providing the matching URL for specific repos for newer OBS instances
             if node.get('url'):
@@ -279,18 +280,13 @@ class Pac:
         self.__dict__.update(self.mp)


-    def makeurls(self, cachedir, urllist, urls = {}):
+    def makeurls(self, cachedir, urllist):

         self.urllist = []
         self.localdir = '%s/%s/%s/%s' % (cachedir, self.project, self.repository, self.arch)
         self.fullfilename = os.path.join(self.localdir, self.canonname)

-        key = '%s/%s' % (self.project, self.repository)
-        if key in urls.keys():
-            self.urllist.append(urls[key] % self.mp)
-            return
-
-        # remote URLs as fallback for old OBS versions, based on downloadurl
+        # remote URLs
         for url in urllist:
             self.urllist.append(url % self.mp)

diff --git a/osc/fetch.py b/osc/fetch.py
index 12b4e4f4..3c1432cb 100644
--- a/osc/fetch.py
+++ b/osc/fetch.py
@@ -38,8 +38,6 @@ class Fetcher:
         self.cachedir = cachedir
         # generic download URL lists
         self.urllist = urllist
-        # path specific URL lists (newer OBS versions)
-        self.urls = {}
         self.modules = modules
         self.http_debug = http_debug
         self.offline = offline
@@ -196,18 +194,26 @@ class Fetcher:
                 print(e, file=sys.stderr)
                 sys.exit(1)

+    def _build_urllist(self, buildinfo, pac):
+        urllist = self.urllist
+        key = '%s/%s' % (pac.project, pac.repository)
+        project_repo_url = buildinfo.urls.get(key)
+        if project_repo_url is not None:
+            urllist = [project_repo_url]
+        return urllist
+
     def run(self, buildinfo):
         cached = 0
-
         all = len(buildinfo.deps)
         for i in buildinfo.deps:
-            i.makeurls(self.cachedir, self.urllist, buildinfo.urls)
+            urllist = self._build_urllist(buildinfo, i)
+            i.makeurls(self.cachedir, urllist)
             # find container extension by looking in the cache
             if i.name.startswith('container:') and i.fullfilename.endswith('.tar.xz'):
                 for ext in ['.tar.xz', '.tar.gz', '.tar']:
                     if os.path.exists(i.fullfilename[:-7] + ext):
                         i.canonname = i.canonname[:-7] + ext
-                        i.makeurls(self.cachedir, self.urllist)
+                        i.makeurls(self.cachedir, urllist)

             if os.path.exists(i.fullfilename):
                 cached += 1
@@ -228,7 +234,6 @@ class Fetcher:
         print("%.1f%% cache miss. %d/%d dependencies cached.\n" % (miss, cached, all))
         done = 1
         for i in buildinfo.deps:
-            i.makeurls(self.cachedir, self.urllist, buildinfo.urls)
             if not os.path.exists(i.fullfilename):
                 if self.offline:
                     raise oscerr.OscIOError(None,


PS: I intentionally dropped the i.makeurls(...) call in the second loop.

**Comment by adrianschroeter** [comment]
I have not looked in detail, but just go ahead and push it!

**Comment by Firstyear** [comment]
@marcus-h Can you tell me when you make this change into a PR so I can test it ....

**Comment by marcus-h** [comment]
On 2021-09-29 09:35:17 +0000, Adrian Schröter wrote:
> I have not looked in detail, but just go ahead and push it!
>
Hmm could you "amend" it in your commit and do a forced push? I would
like to avoid two commits (in order to have a "clean" history).

**Pull request merged**
