### PR TITLE
initial sphinx documentation

### PR DESCRIPTION
**Pull request by cav71**
Hi, this is the pull request update fro the sphinx documentation (as single commit),
I hope this helps

### CODE REVIEW

**Comment by marcus-h** [comment]
Looks (almost:)) great!
Some minor remarks about the tutorial:
- "SuSE build service" -> "open build service"
- "SuSE build projects" -> simply call it "projects"
- avoid synonyms: "workdir" and "working directory" (we should simply
  call it "working copy")

Do you want to update your pull request?:) If not, I can also do the
adjustments on my own (both is fine for me).

Again, thanks for your work!

**Comment by cav71** [comment]
I hope I have updated it..

**Comment by marcus-h** [comment]
On 2016-02-09 13:35:22 -0800, cav71 wrote:
> I hope I have updated it..
> 
Does the doc generation still work for you?

marcus@linux:~/osc/k/osc> python setup.py build_docs
running build_docs
Running Sphinx v1.3.4
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 5 source files that are out of date
updating environment: 5 added, 0 changed, 0 removed
reading sources... [ 40%] api/osc

It "stops" here (100% CPU) - I haven't debugged this further yet (this
happens if I do a fresh checkout of your docs branch).
Which python-sphinx version are you using?

**Comment by cav71** [comment]
It can take a little (secs): it might be some module doing initialization on import. Tonight I'll check what's wrong.
Thanks

On 11 February 2016 13:35:34 GMT+00:00, "Marcus Hüwe" <notifications@github.com> wrote:
>On 2016-02-09 13:35:22 -0800, cav71 wrote:
>> I hope I have updated it..
>> 
>Does the doc generation still work for you?
>
>marcus@linux:~/osc/k/osc> python setup.py build_docs
>running build_docs
>Running Sphinx v1.3.4
>making output directory...
>loading pickled environment... not yet created
>building [mo]: targets for 0 po files that are out of date
>building [html]: targets for 5 source files that are out of date
>updating environment: 5 added, 0 changed, 0 removed
>reading sources... [ 40%] api/osc
>
>It "stops" here (100% CPU) - I haven't debugged this further yet (this
>happens if I do a fresh checkout of your docs branch).
>Which python-sphinx version are you using?
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/openSUSE/osc/pull/187#issuecomment-182865114

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cav71** [comment]
It looks it was spending forever trying to parse some documentation inside osc.core, the latest commit re-organise the imports.
My sphinx version is sphinx 1.3.1,
I hope this helps

**Comment by marcus-h** [comment]
Merged. Thanks a lot for your work (and your patience:) )!

**Pull request merged**
